### ISSUE TITLE
can't find the device

### ISSUE THREAD

**Issue by Yumega** [rytilahti/python-songpal#116]
I'm using sony MT500 but can't find the endpoint

C:\Users\win8.1>songpal discover
Discovering for 5 seconds
INFO:songpal.discovery:Discovering for 5 seconds

**Comment by rytilahti** [comment]
Maybe your system has multiple interfaces, and the MT500 is not connected to the same network that is used by the default network adapter? The discovery is using the default adapter for discovery, and is not currently configurable: https://github.com/rytilahti/python-songpal/blob/master/songpal/discovery.py#L78

**Comment by rytilahti** [comment]
#133 added a way to define the source address for discovery on multihomed setups, so I think this can be closed.
