### ISSUE TITLE
SRS-ZR7 integration connection issues 

### ISSUE THREAD

**Issue by jonaseymour** [rytilahti/python-songpal#119]
Hi, I've been using the songpal HA integration for probably over a year with no issues. In the last week or so my SRS-ZR7 disconnected from HA, and using `songpal discover` also showed nothing, so I figured it was time for a factory reset.

After factory resetting, I was able to see it and get the endpoint through `songpal discover` (it was http://[IP]:54480/sony).
And I was also able to add it successfully to HA with the integration. However, while the device and entity appears in HA, it's unavailable most of the time, and only shows briefly available (less than 1 sec) every 10 seconds or so. See history log below.

Is there any reason that this might be happening?
Is there anything from the `songpal dump-devinfo` I can provide to troubleshoot?

`SRS-ZR7 became unavailable
2:50:57 PM - Now
SRS-ZR7 turned on
2:50:57 PM - Now
SRS-ZR7 became unavailable
2:50:46 PM - 11 seconds ago
SRS-ZR7 turned on
2:50:46 PM - 11 seconds ago
SRS-ZR7 became unavailable
2:50:35 PM - 22 seconds ago
SRS-ZR7 turned on
2:50:35 PM - 22 seconds ago
SRS-ZR7 became unavailable
2:50:24 PM - 33 seconds ago
SRS-ZR7 turned on
2:50:24 PM - 33 seconds ago
SRS-ZR7 became unavailable
2:50:14 PM - 43 seconds ago
SRS-ZR7 turned on
2:50:14 PM - 44 seconds ago
SRS-ZR7 became unavailable
2:50:03 PM - 1 minute ago
SRS-ZR7 turned on
2:50:03 PM - 1 minute ago`

**Comment by rytilahti** [comment]
This is probably a duplicate of https://github.com/home-assistant/core/issues/77730 ? If so, upgrading homeassistant to 2022.9.5 should fix it.

**Comment by jonaseymour** [comment]
Yep, it appears that was the case. Initially had a corrupted upgrade to 2022.9.5, so had to `core rebuild` but after a successful upgrade it's back up and seems stable.
Thanks!
