### ISSUE TITLE
Python 3.11 not supported (asyncio.coroutine has been removed)

### ISSUE THREAD

**Issue by fdecourt** [rytilahti/python-songpal#120]
Hi, 
The script show an error : 
    f = asyncio.coroutine(f)
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

Directly when I run the songpal discover command.

I am using PYTHON 3.11.0rc2

Don't know what to do.
Thanks for your help

**Comment by rytilahti** [comment]
Python 3.11 removes the coroutine decorator, see https://github.com/python/cpython/issues/87382 - For a quick solution, downgrade to earlier python versions. Alternatively, you could try to remove that line with it to see if that's enough to fix it.
