### ISSUE TITLE
Songpal discover giving errors

### ISSUE THREAD

**Issue by NeilS1966** [rytilahti/python-songpal#122]
When I run songpal discover, I get the following message:
`File "/usr/local/lib/python3.10/dist-packages/songpal/discovery.py", line 78, in discover
    await async_search(
TypeError: async_search() got an unexpected keyword argument 'service_type'
`
Songpal version 0.15.1 is installed and I am running python 3.10.6 on PopOS!

I am trying to get an endpoint for my new Sony HT-A7000 so I can use the Home Assistant integration.

**Comment by rytilahti** [comment]
You could either try the linked PR which should fix it or alternatively, downgrade async_upnp_client to 0.31.
