### ISSUE TITLE
Support for SRS-XB23? 

### ISSUE THREAD

**Issue by d3xt3r2909** [rytilahti/python-songpal#127]
Hey, 

Sorry for opening new issue for this thing, but not sure that stackoverlow has enough info about it. I have SRS-XB23 but it seems thats not recognised and since I really don't have enough knowledge  about bluetooth protocols and sony sounds, I need to ask/open this one. 

So, can you help me, is this speaker at all supported by this library, if no could you redirect me to info how did you figure out that/link and which protocol is using .. desperate for useful info :]

Many thanks for your time!

**Comment by rytilahti** [comment]
Hey,

ohh, I googled for that model now and alas it's not supported, sorry. This library only supports wifi (or cabled) devices so I suppose I should update the readme to make it more clear what is being supported.

**Comment by d3xt3r2909** [comment]
Thank you!
