### ISSUE TITLE
Support for TA-AN1000

### ISSUE THREAD

**Issue by dawiinci** [rytilahti/python-songpal#130]
I only get two sources. I can switch it on and off though. 

```
source_list:
  - TV
  - Bluetooth Audio
```
There should be more obviously. 

The receiver is misidentified:

```
Found Receiver - STR-2022
* API version: 1.0
* Endpoint: http://192.168.68.113:10000/sony
  Services:
    - Service: guide
    - Service: audio
    - Service: avContent
    - Service: system
    - Service: appControl
```

Please find dump-devinfo attached:

[dump.txt](https://github.com/rytilahti/python-songpal/files/12044388/dump.txt)

**Comment by rytilahti** [comment]
What kind of sources are you expecting? IIRC, based on some comments in other issues, the external sources (like spotify etc.) are not reported using the API.

The discovery results are based on the device description XML file offered by the device, this might be the reason for "misidentification".

**Comment by ohmantics** [comment]
I've hit the same issue with STR-AZ5000ES. I'm pretty sure it's a bug in the firmware.

I've hit both Sony ES Support and reached out directly to someone to try to get some attention to the issue. Brought it up on their forum [here](https://forum.developer.sony.com/category/7104c629-fa1e-46c9-aebd-d8dbf7e58d9f/topic/42d520c9-6026-4d46-81c5-5478e69a5d60).

**Comment by dawiinci** [comment]
> What kind of sources are you expecting? IIRC, based on some comments in other issues, the external sources (like spotify etc.) are not reported using the API.
> 
> 
> 
> The discovery results are based on the device description XML file offered by the device, this might be the reason for "misidentification".

For example all the HDMI, Blu-ray, etc. The App from Sony works.

**Comment by dawiinci** [comment]
> I've hit the same issue with STR-AZ5000ES. I'm pretty sure it's a bug in the firmware.
> 
> I've hit both Sony ES Support and reached out directly to someone to try to get some attention to the issue. Brought it up on their forum [here](https://forum.developer.sony.com/category/7104c629-fa1e-46c9-aebd-d8dbf7e58d9f/topic/42d520c9-6026-4d46-81c5-5478e69a5d60).

Interesting, but at least the official app works. Also the ports show up in the dump file.

**Comment by rytilahti** [comment]
It could very well be a bug in how this library handles the sources (e.g., maybe it uses a different API?). The simplest way to debug is to capture the traffic between the official app and the device, and then checking how it differs from what this library does.

It could also be that the app does not just use the device-delivered information but has hard-coded entries for some if not all supported devices?

**Comment by ohmantics** [comment]
> It could very well be a bug in how this library handles the sources (e.g., maybe it uses a different API?). The simplest way to debug is to capture the traffic between the official app and the device, and then checking how it differs from what this library does.

The Sony Music Center app no longer uses this API. It uses an entirely UPnP-based one that is harder to sniff because it doesn't obey HTTP proxy settings (it's UDP-based).

I've tested the API calls individually and I'm quite sure it's a bug in the firmware.

**Comment by dawiinci** [comment]
So "harder" means it is possible?

I just need to change the source somehow. Switching on and off including setting volume works though.

**Comment by rytilahti** [comment]
If you are about to reverse-engineer the UPnP-based control protocol, [async_upnp_client](https://github.com/StevenLooman/async_upnp_client#general-set-up) offers a good base to get you started. They support also the eventing which is what you probably mean with the UDP-based part.

The simplest way to sniff the traffic is probably by installing the app in an android emulator and capture all the network traffic to figure out how it works.

**Comment by dawiinci** [comment]
Thanks, I would assume I am not the first one trying this, so maybe it is more difficult?

**Comment by ohmantics** [comment]
> Thanks, I would assume I am not the first one trying this, so maybe it is more difficult?

Please take the time to call Sony Customer Support and report that getSourceList is returning a truncated set of extInput devices instead of the actual set for your receiver.

**Comment by dawiinci** [comment]
I can try that. However, couldn't the plugin just force a source by name?

**Comment by ohmantics** [comment]
> I can try that. However, couldn't the plugin just force a source by name?

Yes, but the point is that the API that's supposed to tell you what the valid sources are is not working properly. Only this year's receivers seem to have this bug.

**Comment by dawiinci** [comment]
Ok, I understand. But until Sony fixes this, a workaround would be nice.

**Comment by dawiinci** [comment]
> > I can try that. However, couldn't the plugin just force a source by name?
> 
> 
> 
> Yes, but the point is that the API that's supposed to tell you what the valid sources are is not working properly. Only this year's receivers seem to have this bug.

So this will work?

`songpal input HDMI1`

Even if it only reported Bluetooth and TV?

Is there any way to define this manually? It probably is almost identical to the previous generation in terms of capability. So maybe faking an older avr would work.

**Comment by allistermaguire** [comment]
Hi, I have the same issue with the STR-AN1000. I have looked at what the Music Center app does, I have duplicated what it does with curl.

Gets the list of external terminals. It lists the zones, and then inputs available for that zone. I only have zone 1 active.

On the STR-AN1000 you can set inputs as hidden, that just seems to set `"iconUrl":""`
```
curl -i -d '{ "method":"getCurrentExternalTerminalsStatus","params":[{}],"version":"1.2","id":5 }' http://xxx.xxx.xxx.xxx:10000/sony/avContent

{"result":[[{"active":"active","connection":"connected","iconUrl":"","label":"","meta":"meta:zone:output","title":"Main Zone","uri":"extOutput:zone?zone=1"},{"active":"inactive","connection":"connected","iconUrl":"","label":"","meta":"meta:zone:output","title":"Zone 2","uri":"extOutput:zone?zone=2"},{"active":"inactive","connection":"connected","iconUrl":"","label":"","meta":"meta:zone:output","title":"Zone 3","uri":"extOutput:zone?zone=3"},{"active":"active","connection":"connected","iconId":"game","iconUrl":"","label":"","meta":"meta:game","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=2"],"title":"GAME","uri":"extInput:game"},{"active":"active","connection":"connected","iconId":"media_box","iconUrl":"","label":"","meta":"meta:mediaBox","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=2"],"title":"MEDIA BOX","uri":"extInput:mediaBox"},{"active":"active","connection":"connected","iconId":"","iconUrl":"","label":"","meta":"meta:bd-dvd","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=2"],"title":"","uri":"extInput:bd-dvd"},{"active":"active","connection":"connected","iconId":"","iconUrl":"","label":"","meta":"meta:sat-catv","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=2","extOutput:zone?zone=3"],"title":"","uri":"extInput:sat-catv"},{"active":"active","connection":"connected","iconId":"","iconUrl":"","label":"","meta":"meta:video","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=2"],"title":"","uri":"extInput:video"},{"active":"active","connection":"connected","iconId":"","iconUrl":"","label":"","meta":"meta:line","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=3"],"title":"","uri":"extInput:line"},{"active":"active","connection":"connected","iconId":"","iconUrl":"","label":"","meta":"meta:sacd-cd","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=2","extOutput:zone?zone=3"],"title":"","uri":"extInput:sacd-cd"},{"active":"active","connection":"connected","iconUrl":"","label":"","meta":"meta:btaudio","outputs":["extOutput:zone?zone=1"],"title":"Bluetooth Audio","uri":"extInput:btAudio"},{"active":"active","connection":"connected","iconUrl":"","label":"","meta":"meta:source","outputs":["extOutput:zone?zone=2","extOutput:zone?zone=3"],"title":"SOURCE","uri":"extInput:source"},{"active":"active","connection":"connected","iconId":"tv","iconUrl":"","label":"","meta":"meta:tv","outputs":["extOutput:zone?zone=1","extOutput:zone?zone=3"],"title":"TV","uri":"extInput:tv"}]],"id":5}%
```
It then queries the playback function for the zone to get the active input.
```
curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[{"output":"extOutput:zone?zone=1"}],"version":"1.0","id":6 }' http://xxx.xxx.xxx.xxx:10000/sony/avContent

{"result":[[{"functions":[],"output":"extOutput:zone?zone=1","uri":"extInput:mediaBox"}]],"id":8}% 
```

If I do the same thing via custom commands, I get the following.
```
songpal --endpoint http://xxx.xxx.xxx.xxx:10000/sony command avContent getCurrentExternalTerminalsStatus                                  
Calling avContent.getCurrentExternalTerminalsStatus with params None
INFO:songpal.device:Calling avContent.getCurrentExternalTerminalsStatus(None)
[{'active': 'active', 'connection': 'connected', 'iconUrl': '', 'label': '', 'meta': 'meta:tv', 'title': 'TV', 'uri': 'extInput:tv'}, {'active': 'active', 'connection': 'connected', 'iconUrl': '', 'label': '', 'meta': 'meta:btaudio', 'title': 'Bluetooth Audio', 'uri': 'extInput:btAudio'}]
```
```
songpal --endpoint http://xxx.xxx.xxx.xxx:10000/sony command avContent getAvailablePlaybackFunction '{"output":"extOutput:zone?zone=1"}'
Calling avContent.getAvailablePlaybackFunction with params {'output': 'extOutput:zone?zone=1'}
INFO:songpal.device:Calling avContent.getAvailablePlaybackFunction({'output': 'extOutput:zone?zone=1'})
[{'functions': [], 'output': 'extOutput:zone?zone=1', 'uri': 'extInput:mediaBox'}]
```

I have found the issue with `getCurrentExternalTerminalsStatus` and therefore `songpal zone` and `songpal input` don't work. The STR-AN1000 supports both version 1.0 and 1.2 of `getCurrentExternalTerminalsStatus`, and version 1.0 doesn't return all the data. The `getMethodTypes` returns version 1.2, but it gets ignored.
```
DEBUG:songpal.service:Got duplicate signature for MethodSignature(name='getCurrentExternalTerminalsStatus', input={'uri': <class 'str'>}, output={'uri': <class 'str'>, 'title': <class 'str'>, 'connection': <class 'str'>, 'active': <class 'str'>, 'label': <class 'str'>, 'outputs': 'string*', 'meta': <class 'str'>, 'iconUrl': <class 'str'>, 'avOutput': <class 'str'>, 'iconId': <class 'str'>}, version='1.2'), existing was <Method avContent.getCurrentExternalTerminalsStatus(None) -> {'active': <class 'str'>,
 'connection': <class 'str'>,
 'iconUrl': <class 'str'>,
 'label': <class 'str'>,
 'meta': <class 'str'>,
 'outputs': 'string*',
 'title': <class 'str'>,
 'uri': <class 'str'>}>, keeping it.
```
I have only briefly looked at the logic and don't understand what it is checking against, but if I remove the check and use the returned version I can make the `getCurrentExternalTerminalsStatus` work if I add params to the end.
```
songpal --endpoint http://xxx.xxx.xxx.xxx:10000/sony command avContent getCurrentExternalTerminalsStatus '{}'
```
That doesn't fix `songpal zone` and `songpal input`, as version 1.2 request requires params. It says it needs `uri` but works fine with `{}`. But `get_zones()` and `get_inputs()` don't send params. If I update that I can make both of those work.

So almost there. The next issue is that the STR-AN1000 doesn't get the active input from `getCurrentExternalTerminalsStatus` but by using `getAvailablePlaybackFunction` instead. So to be able to ensure `songpal input` returns which input is active, changes would be needed for `class Input:` to use data returned from `getAvailablePlaybackFunction` instead.

Interestingly, if it was changed to this method, it also works for Spotify (only tested on the STR-AN1000)
```
songpal --endpoint http://xxx.xxx.xxx.xxx:10000/sony command avContent getAvailablePlaybackFunction '{"output":"extOutput:zone?zone=1"}'      
Calling avContent.getAvailablePlaybackFunction with params {'output': 'extOutput:zone?zone=1'}
INFO:songpal.device:Calling avContent.getAvailablePlaybackFunction({'output': 'extOutput:zone?zone=1'})
[{'functions': [{'function': 'playback', 'isAvailable': True}, {'function': 'stop', 'isAvailable': True}, {'function': 'pause', 'isAvailable': True}, {'function': 'fwdScan', 'isAvailable': True}, {'function': 'bwdScan', 'isAvailable': True}, {'function': 'next', 'isAvailable': True}, {'function': 'prev', 'isAvailable': True}], 'output': 'extOutput:zone?zone=1', 'uri': 'netService:audio?service=spotify'}]
```

There are other calls broken like `songpal source` for example, but I haven't looked into any others as I only use this with Home Assistant.

I wasn't sure if I should continue the conversation in this issue, or create a new one.

**Comment by rytilahti** [comment]
So looks like that the `getMethodTypes()` output is used to figure out the available methods: https://github.com/rytilahti/python-songpal/blob/a089e917af57114d5f7f94a5790c25040ce89c79/songpal/service.py#L104-L114 - if the same method has multiple versions, the definitions coming earlier are preferred. At the moment the version information is not used anywhere, so adding some logic around handling them would be necessary to support multiple versions and to avoid breaking existing setups.

I have not personally used my HT-XT3 for years now, but I can prepare releases as needed if you wish to contribute PRs to improve the support for newer versions. :-)

**Comment by allistermaguire** [comment]
Thank you for the response, makes sense. The `dump-devinfo` only dumps the last version for each method which threw me off.

I can have a go, I haven't been a developer for a very long time, more just know enough to be dangerous :)

I just sold my STR-DN1080, but got some packet captures beforehand so I can compare things. The Music Center app uses `getAvailablePlaybackFunction` to retrieve the active input as well, so the method used on the STR-AN1000 seems to be used for at least one older device as well.

The other annoying thing I have found is that there is a slight change with the `notifyPlayingContentInfo` notification without incrementing the version.

STR-AN1000
```
{"method":"notifyPlayingContentInfo","params":[{"kind":"input","output":"extOutput:zone?zone=1","service":"","source":"extInput:game","uri":"extInput:game"}],"version":"1.0"}
```
STR-DN1080
```
{"method":"notifyPlayingContentInfo","params":[{"contentKind":"input","output":"extOutput:zone?zone=1","source":"extInput:game","uri":"extInput:game"}],"version":"1.0"}
```

I have hacked a version together to see if I could make all the input functionality work in Hass with my newer STR-AN1000. So at least I know I can make it work, and be backward compatible with the DN1080 (except for the notification at the moment).

**Comment by dawiinci** [comment]
Thanks for your efforts. 

Let me know if I can be helpful by testing it.

**Comment by allistermaguire** [comment]
I created a pull request if you want to have a look and try it. It is pretty crude, but it is working.

**Comment by dawiinci** [comment]
Thanks, I will try that. 

Installed using pip install git+https://github.com/allistermaguire/python-songpal

I still only get Bluetooth and TV.

```
$songpal discover

Found Receiver - STR-2022
* API version: 1.0
* Endpoint: http://192.168.68.11:10000/sony
  Services:
    - Service: guide
    - Service: audio
    - Service: avContent
    - Service: system
    - Service: appControl

[UPnP]
* URL: http://192.168.68.11:54380/MediaRenderer_TA-AN1000.xml
* UDN: uuid:000000....
  Services:
    - Service: urn:schemas-upnp-org:service:RenderingControl:1
    - Service: urn:schemas-upnp-org:service:ConnectionManager:1
    - Service: urn:schemas-upnp-org:service:AVTransport:1
    - Service: urn:schemas-sony-com:service:ScalarWebAPI:1
```


In Home Assistant I get only this - unchanged to the original songpal:
```
source_list:
  - TV
  - Bluetooth Audio
volume_level: 0.13513513513513514
is_volume_muted: false
source: Bluetooth Audio
friendly_name: TA-AN1000
supported_features: 3468

```

Am I doing something wrong?

**Comment by allistermaguire** [comment]
Hi @dawiinci, I am not sure how your Home Assistant is setup, and if the `pip install..` will work. But you should be able to test if the newer version of python-songpal can get the information needed from your receiver. What do you get with the following commands?
```
songpal --endpoint http://192.168.68.11:10000/sony zone
songpal --endpoint http://192.168.68.11:10000/sony input
```
Unfortunately, I didn't update the version so you can't even check the songpal version to see if it is the correct one.

**Comment by ohmantics** [comment]
@allistermaguire With #131 installed via poetry into a venv, `songpal input` now shows a much better set of inputs for my STR-AZ5000ES:
```Inputs:
  * PS5 (uri: extInput:game)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=2
  * AppleTV (uri: extInput:mediaBox) (active)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=2
  * BD/DVD (uri: extInput:bd-dvd)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=2
  * PS3 (uri: extInput:sat-catv)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=2
    - extOutput:zone?zone=3
  * VIDEO (uri: extInput:video)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=2
  * AUX (uri: extInput:line)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=2
    - extOutput:zone?zone=3
  * SA-CD/CD (uri: extInput:sacd-cd)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=2
    - extOutput:zone?zone=3
  * TV (uri: extInput:tv)
    - extOutput:zone?zone=1
    - extOutput:zone?zone=3
```
As noted, `songpal source` is broken:
```TV (extInput:tv)
HDMI1 (extInput:hdmi?port=1)
  Got an error for getContentCount: [3, 'Illegal Argument']: IllegalArgument (3): Illegal Argument
HDMI2 (extInput:hdmi?port=2)
  Got an error for getContentCount: [3, 'Illegal Argument']: IllegalArgument (3): Illegal Argument
Bluetooth Audio (extInput:btAudio)
Analog (extInput:line)
AirPlay (extInput:airPlay)
USB (storage:usb1)
  Got an error for getContentCount: [3, 'Illegal Argument']: IllegalArgument (3): Illegal Argument
Home Network (dlna:music)
Unable to get sources for radio: Got an error for getSourceList: [3, 'Illegal Argument']: IllegalArgument (3): Illegal Argument
NetService (netService:audio)
```

**Comment by allistermaguire** [comment]
Thanks @ohmantics. It isn't actually that difficult to fix the `songpal source` issue as well. What I have done is more of a test, Hass only uses some of the functionality. I fixed up `songpal speaker` as I use that to update speaker distance values depending on if I am playing Xbox or watching TV/Movie, as I sit closer to the TV playing games.

I submitted the PR to progress the conversation/feedback, but I think it would be good to refactor the way the signatures/API methods are currently stored/referenced so it is easier to support different versions. The idea is to see what @rytilahti might want to do.

**Comment by ohmantics** [comment]
@allistermaguire Any ideas about getSourceList 1.3? I've tried passing scheme: extInput and it returns illegal argument for that scheme, but works for all the others I've tried.

**Comment by allistermaguire** [comment]
@ohmantics The 'Music Center' app doesn't use `{"scheme":"extInput"}` with `getSourceList`. Even for my STR-DN1080 where the API works fine. It queries `getSchemeList` and then iterates through all but ignores `extInput`. For `extInput` it relies on `getCurrentExternalTerminalsStatus`. It then uses `getAvailablePlaybackFunction` to return which one is active. These are what are used for `songpal input`. `songpal zone` uses `getCurrentExternalTerminalsStatus`.

I did think about combining `source` with `input`, that way you would have all inputs. I wanted Spotify to show. But it makes sense to keep them separate as they are different things and it doesn't break the model. You would combine them in say Home Assistant code, or whatever client app you are using.

Version 1.3 of `getSourceList` would fix the issues for the sources. But `songpal source` also uses `getContentCount`. It throws illegal argument errors because it wants `uri` parameter and not `target` which is being sent.

The version hasn't been incremented so the simple list hack I used would not work in this case. The `getMethodTypes` does provide what the parameters should be, so if the construction of the requests were dynamically based on `getMethodTypes`, then you could cover this and other scenarios like it.

**Comment by dawiinci** [comment]
> What do you get with the following commands?
> 
> ```
> songpal --endpoint http://192.168.68.11:10000/sony zone
> songpal --endpoint http://192.168.68.11:10000/sony input
> ```

@allistermaguire 
This is what I get:
```
$Zones:
Error: Device has no zones: None
Inputs:
  * TV (uri: extInput:tv) (active)
  * Bluetooth Audio (uri: extInput:btAudio) (active)
```

**Comment by allistermaguire** [comment]
@dawiinci That implies that either it isn't using my updated version or my updates do not work for your device. I have tried the `pip` command on my Macbook and it works as expected, but I did not have python-songpal previously installed. Because it is the same version it might not install over the top.

I would also recommend that you use the 'Dev' branch which is a little nicer. I have created version `0.15.3` so you will be able to tell which version you have installed. The current version is `0.15.2`. You can install it with:
```
pip3 install git+https://github.com/allistermaguire/python-songpal.git@0.15.3
```
You should see this at the end of the pip install
```
Installing collected packages: python-songpal
Successfully installed python-songpal-0.15.3
```
and this is the cli app
```
% songpal --version
songpal, version 0.15.3
```

**Comment by allistermaguire** [comment]
Added a newer version that has some refactoring and support for `getSourceList` version `1.3`.
```
pip3 install git+https://github.com/allistermaguire/python-songpal.git@0.15.5
```
Note cli app `songpal source` still throws errors, but they are app errors, not library errors. It is trying to get a content list of each source. This is what the output would look like with those removed:
```
Unable to get sources for extInput: Scheme not supported in version 1.3, use get_inputs() instead: None
USB (storage:usb1) - outs: ['extOutput:zone?zone=1']
Home Network (dlna:music) - outs: ['extOutput:zone?zone=1']
FM (radio:fm) - outs: ['extOutput:zone?zone=1', 'extOutput:zone?zone=3']
NetService (netService:audio)
```

**Comment by dawiinci** [comment]
Thanks, it seems to work. Unfortunately Home Assistant won't update the device. If I remove it manually it installs the old version first. 

I guess I have to wait until the PR is accepted. 

Thanks for your work.

**Comment by allistermaguire** [comment]
Thank you for the info. Home Assistant has a specified required version so will reinstall the older published version.

If/when this PR gets accepted, another will need to be raised in Hass to bump the dependency, so it will take a little while.

If you don't want to wait you can uninstall the old version and install this version like you did, but before restarting Hass update the version in `/usr/src/homeassistant/homeassistant/components/songpal/manifest.json` (assuming this is where you have it installed). Note, that whenever you upgrade Hass, you will need to repeat the process.

**Comment by dawiinci** [comment]
I am glad to report it works perfectly in Home Assistant as well. 

Thanks a lot.

**Comment by rytilahti** [comment]
Glad to see that you figured it all out, @allistermaguire! I'll take a look at your PR later, probably next weekend, and give it a brief test with the ht-xt3, if it still boots.

Btw, home assistant can also be launched with `--skip-pip` to instruct it not to use pip to download and install the dependencies.

**Comment by rytilahti** [comment]
Fixed by #132, thanks a lot to @allistermaguire! :100:

**Comment by dawiinci** [comment]
Thanks, when do you release the new version?

**Comment by rytilahti** [comment]
New release is now available: https://github.com/rytilahti/python-songpal/releases/tag/release%2F0.16

**Comment by Kuchiru** [comment]
@dawiinci 
Apologies for asking this in a closed ticket but i was unable to find any other mention of the TA-AN1000 and home assistant.
I'm looking to get this unit soon and was looking around how the support for this device was in home assistant.
What can i expect to do (or not) with home assistant with this device?

Things like seeing the audio channel/source (tv audio or anything else) sending play/pause commands or changing the volume.

**Comment by dawiinci** [comment]
Yes this is possible. I use volume changes and channel selection frequently. Also powering on and off works. Works pretty well.
