### ISSUE TITLE
Can't Add STRDN1080 Amp - But Home Assistant Pi Can cURL, and see as Chromecast Device

### ISSUE THREAD

**Issue by old-square-eyes** [rytilahti/python-songpal#142]
Edit: SOLVED. See comment.

Songpal controls used to work, but have stopped. I can connect to my amp from the Pi with cURL.

Adding it as a device manually fails. It's not clear whether to use IP or full url, but neither work. Tried various versions of the below... 

http://192.168.X.XX:10000/sony/system

![image](https://github.com/rytilahti/python-songpal/assets/25760491/7e64189c-0b10-419f-ac54-79f9ac507ee5)

In some ways it feels like it's set up already. But there are no Songpal controls like volume, input channel... like there used to be.

I deleted and re-added a tile but it's just a Google Cast tile with a power control, not the full control I had before. Incidentally the device also doesn't appear in my Android Music Center app any more either and they seem to have removed manual setup via IP.

<img width="1435" alt="image" src="https://github.com/rytilahti/python-songpal/assets/25760491/9b107c96-d29a-49aa-91d7-050b62efc173">

<img width="474" alt="image" src="https://github.com/rytilahti/python-songpal/assets/25760491/82b791e6-fc2e-4493-aa5d-98a6fa8d9a6c">

**Comment by old-square-eyes** [comment]
Solved. Deleted Songpal Integration and re-added. Endpoint format is http://192.168.X.XX:10000/sony/

It would be helpful if the setup pane displayed the required format.

**Comment by rytilahti** [comment]
Feel free to improve the homeassistant documentation on this regard! Having it written down in the documentation would be a great help for anyone else stumbling upon the very same issue :-)

This report made me wonder if the songpal integration (which I haven't used for some years now) does automatically update the config entries on IP address changes. The issue you had to my understanding was that the IP address of the device changed, so homeassistant didn't know where the endpoint is. Re-triggering the discovery process made it to perform the discovery again and discovered the device with the new IP address.

It may very well be, that updating config entries on ssdp responses wasn't supported back then by homeassistant and and it might be still a bit tricky (as the endpoint information is not contained in the advertisemenets, but inside a separate device description file whose location is stored in the ssdp advertisements. I doubt the location changes on these devices, so it'd be fairly risk-free to update the endpoint URL on address changes.

If someone wants to improve the integration, I'm still marked as the codeowner and will receive notifications on pull requests and can thus perform reviews, but I'm not personally going to invest in time on developing the integration further in the foreseeable future.
