### ISSUE TITLE
https://github.com/rytilahti/python-songpal/pull/132 breaks support for SRS-X77

### ISSUE THREAD

**Issue by RobertBuhren** [rytilahti/python-songpal#144]
Hi all,

I started to have issues with my SRS-X77 recently and a git bisect revealed that https://github.com/rytilahti/python-songpal/pull/132 introduced an issue for me: Commands such as ` songpal status`  started to emit this error:
` 
 ~ songpal --endpoint http://192.168.178.27:54480/sony status
Power off
Volume: 6/30
Not playing any media
Error: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation
`
Commits before pulling in  https://github.com/rytilahti/python-songpal/pull/132 work fine.

This breaks the usage of python-songpal in homeassitant for me.

Regards,

Robert

**Comment by RobertBuhren** [comment]
Debug log:

  ~ songpal --debug --endpoint http://192.168.178.27:54480/sony status
Setting debug level to 1
DEBUG:root:Using endpoint http://192.168.178.27:54480/sony
DEBUG:songpal.device:Endpoint: http://192.168.178.27:54480/sony
DEBUG:songpal.device:Guide endpoint: http://192.168.178.27:54480/sony/guide
DEBUG:songpal.device:Got 4 services!
DEBUG:songpal.service:Available protocols for audio: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyVolumeInformation', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyVolumeInformation, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/audio>]
DEBUG:songpal.service:Available protocols for avContent: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyAvailablePlaybackFunction', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifyPlayingContentInfo',
 'versions': [{'authLevel': 'private', 'version': '1.0'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyAvailablePlaybackFunction, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/avContent>, <Notification notifyPlayingContentInfo, versions=[{'authLevel': 'private', 'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/avContent>]
DEBUG:songpal.service:Available protocols for guide: ['xhrpost:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.XHRPost
DEBUG:songpal.service:Available protocols for system: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyPowerStatus', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifySWUpdateInfo', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifySettingsUpdate', 'versions': [{'version': '1.1'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifyStorageStatus',
 'versions': [{'authLevel': 'generic', 'version': '1.1'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyPowerStatus, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/system>, <Notification notifySWUpdateInfo, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/system>, <Notification notifySettingsUpdate, versions=[{'version': '1.1'}], endpoint=http://192.168.178.27:54480/sony/system>, <Notification notifyStorageStatus, versions=[{'authLevel': 'generic', 'version': '1.1'}], endpoint=http://192.168.178.27:54480/sony/system>]
DEBUG:songpal.service:getPowerStatus version 1.1 got called with args (()) kwargs ({})
DEBUG:songpal.method:got res: {'id': 6, 'result': [{'status': 'standby'}]}
DEBUG:songpal.containers:Missing key standbyDetail with no default for Power
Power off
DEBUG:songpal.service:getVolumeInformation version 1.1 got called with args (({},)) kwargs ({})
DEBUG:songpal.method:got res: {'id': 7,
 'result': [[{'maxVolume': 30,
              'minVolume': 0,
              'mute': 'off',
              'step': 0,
              'volume': 6}]]}
DEBUG:songpal.containers:Missing key output with no default for Volume
Volume: 6/30
DEBUG:songpal.service:getPlayingContentInfo version 1.2 got called with args (({},)) kwargs ({})
DEBUG:songpal.method:got res: {'id': 8,
 'result': [[{'contentKind': 'service',
              'fileNo': '255',
              'parentUri': '',
              'service': 'netService:audio?service=spotify',
              'source': 'netService:audio',
              'stateInfo': {'state': 'STOPPED', 'supplement': ''},
              'uri': 'netService:audio?service=spotify&contentId=-1'}]]}
DEBUG:songpal.containers:Got unknowns for PlayInfo: {'services': {'audio': <Service audio: 10 methods, 1 notifications, protocols: [] (active: ProtocolType.WebSocket), 'avContent': <Service avContent: 24 methods, 2 notifications, protocols: [] (active: ProtocolType.WebSocket), 'guide': <Service guide: 4 methods, 0 notifications, protocols: [] (active: ProtocolType.XHRPost), 'system': <Service system: 22 methods, 4 notifications, protocols: [] (active: ProtocolType.WebSocket)}, 'fileNo': '255'} - please create an issue!
DEBUG:songpal.containers:Missing key output with no default for PlayInfo
DEBUG:songpal.containers:Missing key applicationName with no default for PlayInfo
DEBUG:songpal.containers:Missing key artist with no default for PlayInfo
DEBUG:songpal.containers:Missing key albumName with no default for PlayInfo
DEBUG:songpal.containers:Missing key title with no default for PlayInfo
DEBUG:songpal.containers:Missing key durationMsec with no default for PlayInfo
DEBUG:songpal.containers:Missing key mediaType with no default for PlayInfo
DEBUG:songpal.containers:Missing key positionMsec with no default for PlayInfo
DEBUG:songpal.containers:Missing key repeatType with no default for PlayInfo
DEBUG:songpal.containers:Missing key content with no default for PlayInfo
Not playing any media
DEBUG:songpal.service:getAvailablePlaybackFunction version 1.0 got called with args (()) kwargs ({'output': ''})
DEBUG:songpal.method:<Method avContent.getAvailablePlaybackFunction({'output': <class 'str'>}) -> {'functions': 'FunctionInfo[]', 'output': <class 'str'>, 'uri': <class 'str'>} version 1.0>
Error: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation
Traceback (most recent call last):
  File "/home/robert/songpal_venv/bin/songpal", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/main.py", line 56, in wrapper
    raise ex
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/main.py", line 47, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/main.py", line 172, in status
    outs = await dev.get_inputs()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/device.py", line 282, in get_inputs
    active_input_uri = (await self.get_available_playback_functions())[0].uri
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/device.py", line 478, in get_available_playback_functions
    for x in await self.services["avContent"]["getAvailablePlaybackFunction"](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/method.py", line 134, in __call__
    raise SongpalException(
songpal.common.SongpalException: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation

**Comment by rytilahti** [comment]
@allistermaguire mind taking a peek into how easily this regression could be fixed? :-)

**Comment by allistermaguire** [comment]
Hi @RobertBuhren, sorry for the inconvenience. I can see what call is the issue but would like to understand why it doesn't work for your device.

Can you please help me by providing the output for the two commands below?
```
songpal --debug --endpoint http://192.168.178.27:54480/sony command avContent getAvailablePlaybackFunction {}
```
```
curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[{"output":""}],"version":"1.0","id":11 }' http://192.168.178.27:54480/sony/avContent
```

Thanks
Allister

**Comment by RobertBuhren** [comment]
> Hi @RobertBuhren, sorry for the inconvenience. I can see what call is the issue but would like to understand why it doesn't work for your device.
> 
> Can you please help me by providing the output for the two commands below?

Sure, thanks for the quick reply.

> 
> ```
> songpal --debug --endpoint http://192.168.178.27:54480/sony command avContent getAvailablePlaybackFunction {}
> ```
> 

`songpal --debug --endpoint http://192.168.178.27:54480/sony command avContent getAvailablePlaybackFunction {}
Setting debug level to 1
DEBUG:root:Using endpoint http://192.168.178.27:54480/sony
DEBUG:songpal.device:Endpoint: http://192.168.178.27:54480/sony
DEBUG:songpal.device:Guide endpoint: http://192.168.178.27:54480/sony/guide
DEBUG:songpal.device:Got 4 services!
DEBUG:songpal.service:Available protocols for audio: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyVolumeInformation', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyVolumeInformation, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/audio>]
DEBUG:songpal.service:Available protocols for avContent: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyAvailablePlaybackFunction', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifyPlayingContentInfo',
 'versions': [{'authLevel': 'private', 'version': '1.0'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyAvailablePlaybackFunction, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/avContent>, <Notification notifyPlayingContentInfo, versions=[{'authLevel': 'private', 'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/avContent>]
DEBUG:songpal.service:Available protocols for guide: ['xhrpost:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.XHRPost
DEBUG:songpal.service:Available protocols for system: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyPowerStatus', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifySWUpdateInfo', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifySettingsUpdate', 'versions': [{'version': '1.1'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifyStorageStatus',
 'versions': [{'authLevel': 'generic', 'version': '1.1'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyPowerStatus, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/system>, <Notification notifySWUpdateInfo, versions=[{'version': '1.0'}], endpoint=http://192.168.178.27:54480/sony/system>, <Notification notifySettingsUpdate, versions=[{'version': '1.1'}], endpoint=http://192.168.178.27:54480/sony/system>, <Notification notifyStorageStatus, versions=[{'authLevel': 'generic', 'version': '1.1'}], endpoint=http://192.168.178.27:54480/sony/system>]
Calling avContent.getAvailablePlaybackFunction with params {}
INFO:songpal.device:Calling avContent.getAvailablePlaybackFunction({})
DEBUG:songpal.service:getAvailablePlaybackFunction version 1.0 got called with args (({},)) kwargs ({})
DEBUG:songpal.method:<Method avContent.getAvailablePlaybackFunction({'output': <class 'str'>}) -> {'functions': 'FunctionInfo[]', 'output': <class 'str'>, 'uri': <class 'str'>} version 1.0>
Error: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation
Traceback (most recent call last):
  File "/home/robert/songpal_venv/bin/songpal", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/main.py", line 56, in wrapper
    raise ex
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/main.py", line 47, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/main.py", line 626, in command
    res = await dev.raw_command(service, method, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/device.py", line 567, in raw_command
    return await self.services[service][method](params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert/songpal_venv/lib/python3.11/site-packages/songpal/method.py", line 134, in __call__
    raise SongpalException(
songpal.common.SongpalException: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation

> ```
> curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[{"output":""}],"version":"1.0","id":11 }' http://192.168.178.27:54480/sony/avContent
> ```

curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[{"output":""}],"version":"1.0","id":11 }' http://192.168.178.27:54480/sony/avContent
HTTP/1.1 200 OK
Connection: close
Content-Length: 46
Content-Type: application/json

{"error":[15,"unsupported operation"],"id":11}%


> 
> Thanks Allister

**Comment by allistermaguire** [comment]
Thanks @RobertBuhren. That error is apparently `The server cannot handle the request with the specified parameters` ideally one of the two commands I gave you would have worked. I am not sure if it is just not implemented even though `getMethodType` says it is and it is returning the incorrect error, or it just doesn't adhere the the method spec.

I have a fix, if you can please try installing this version and let me know?
```
pip3 install git+https://github.com/allistermaguire/python-songpal.git@0.16.1
```

if you could also try these commands? I want to see if your device returns the correct errors. FYI, should be Error 12, 15 (curl version of the songpal command I gave you), 3 respectively.
```
curl -i -d '{ "method":"getAvailablePlaybackFunctions","params":[{"output":""}],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
```
```
curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[{}],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
```
```
curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
```
I appreciate you providing the time to collect this info for me.

Thanks, Allister

**Comment by RobertBuhren** [comment]
> https://github.com/allistermaguire/python-songpal.git



> Thanks @RobertBuhren. That error is apparently `The server cannot handle the request with the specified parameters` ideally one of the two commands I gave you would have worked. I am not sure if it is just not implemented even though `getMethodType` says it is and it is returning the incorrect error, or it just doesn't adhere the the method spec.
> 
> I have a fix, if you can please try installing this version and let me know?
> 
> ```
> pip3 install git+https://github.com/allistermaguire/python-songpal.git@0.16.1

I can confirm that this version does not show an error message for ` songpal status`  :

```
  ~/songpal_tmp/python-songpal songpal --endpoint http://192.168.178.27:54480/sony status
Power off
Volume: 8/30
Not playing any media
System information: Sysinfo(bdAddr='B8:86:87:99:62:B3', macAddr='ac:9b:0a:78:06:67', version='1.60.3351', wirelessMacAddr='40:b8:9a:a3:41:f5', bssid=None, ssid='FRITZ!Box 6690 NR', bleID=None, serialNumber=None, generation=None, model=None)

```


> 
> 
> if you could also try these commands? I want to see if your device returns the correct errors. FYI, should be Error 12, 15 (curl version of the songpal command I gave you), 3 respectively.
> 
> ```
> curl -i -d '{ "method":"getAvailablePlaybackFunctions","params":[{"output":""}],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
> ```
```

 ~/songpal_tmp/python-songpal curl -i -d '{ "method":"getAvailablePlaybackFunctions","params":[{"output":""}],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
HTTP/1.1 200 OK
Connection: close
Content-Length: 54
Content-Type: application/json

{"error":[12,"getAvailablePlaybackFunctions"],"id":12}%
```

> 
> ```
> curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[{}],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
> ```

```
  ~/songpal_tmp/python-songpal curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[{}],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
HTTP/1.1 200 OK
Connection: close
Content-Length: 46
Content-Type: application/json

{"error":[15,"unsupported operation"],"id":12}%

```


> 
> ```
> curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
> ```
> 
```
  ~/songpal_tmp/python-songpal curl -i -d '{ "method":"getAvailablePlaybackFunction","params":[],"version":"1.0","id":12 }' http://192.168.178.27:54480/sony/avContent
HTTP/1.1 200 OK
Connection: close
Content-Length: 40
Content-Type: application/json

{"error":[3,"Illegal Argument"],"id":12}%

```

> I appreciate you providing the time to collect this info for me.
> 
> Thanks, Allister


Thank you for your effort. Let me know if you need anything else.

Regards,

Robert

**Comment by allistermaguire** [comment]
Thank you @RobertBuhren for the info, that all seems to be aligned with the API spec. I am not sure what combo or params are needed for that method to work with the SRS-X77. It doesn't impact on a fix. I have submitted a PR for you @rytilahti
