### ISSUE TITLE
Can't find endpoint SRS-X88

### ISSUE THREAD

**Issue by seanb-uk** [rytilahti/python-songpal#2]
First of all, glad to see this, I've got an SRS-X88 speaker that I've been wanting to integrate into Home Assistant!

I see endpoint is now a compulsory option even when attempting to discover. The discovery doesn't work, and I've tried various endpoints based on your example of http://<ip_address>:10000/sony with no luck. I've tried directly against all of the ports shown open in nmap:
```
PORT      STATE SERVICE
80/tcp    open  http
5000/tcp  open  upnp
8008/tcp  open  http
8009/tcp  open  ajp13
9876/tcp  open  sd
10001/tcp open  scp-config
```

The http ports return 404 for /sony if I try them in a browser.

The speaker does work with the Songpal app and http://<ip_address> returns a network device settings page.

Any ideas on how I can find the right endpoint?

**Comment by rytilahti** [comment]
Ah, I overlooked the issue with endpoint w/ discovery mode, it's enough to pass any parameter to it in that case, and I'll fix that at some point.

For discovering the endpoint you could try passing `--debug` as the first parameter to get some debug output from the upnpclient library. Search for `sony` or something similar, this is what's discovered here:
```
DEBUG:Device:http://192.168.XX.XX:52323/dmr.xml: Service 'urn:schemas-sony-com:service:ScalarWebAPI:1' at '/ScalarWebApiSCPD.xml'
```
The endpoint information should be listed in that `dmr.xml` file (this is from where discover tries to look for it), not in `/ScalarWebApiSCPD.xml`!

edit: To add, the discovery needs to be run on a device which is located in the same network as the songpal device / one needs to do a traffic capture from that network and look for SSDP announcements.

edit2: here's a copy&paste from `dmr.xml` of HT-XT3 what the discover looks for:
```
    <av:X_ScalarWebAPI_DeviceInfo>
      <av:X_ScalarWebAPI_Version>1.0</av:X_ScalarWebAPI_Version>
      <av:X_ScalarWebAPI_BaseURL>http://192.168.XX.XX:10000/sony</av:X_ScalarWebAPI_BaseURL>
      <av:X_ScalarWebAPI_ServiceList>
        <av:X_ScalarWebAPI_ServiceType>guide</av:X_ScalarWebAPI_ServiceType>
        <av:X_ScalarWebAPI_ServiceType>system</av:X_ScalarWebAPI_ServiceType>
        <av:X_ScalarWebAPI_ServiceType>audio</av:X_ScalarWebAPI_ServiceType>
        <av:X_ScalarWebAPI_ServiceType>avContent</av:X_ScalarWebAPI_ServiceType>
      </av:X_ScalarWebAPI_ServiceList>
    </av:X_ScalarWebAPI_DeviceInfo>
```

**Comment by seanb-uk** [comment]
UPnP isn't picking up anything from the IP address of the device. It might be because the Sony is on wifi, and the device I'm discovering from is on wired ethernet, although they are on the same subnet. I was hoping to be able to target the device directly.

If I get a chance I'll take it down to my router and try it wired in and see if it makes any difference. Worst case I might be able to see what the official app is doing.

**Comment by rytilahti** [comment]
I'm also using mine on wifi, maybe your router is doing some filtering? Anyway, targeting the device directly can be a bit difficult, you could try if you can download the `dmr.xml` file from the port shown above. I wouldn't count on those ports (either SSDP XML nor the endpoint) being static, that's why I built the discovery in :-)

**Comment by seanb-uk** [comment]
Ah, if I turn off the firewall on the machine from which I'm running the discovery I can discover the device which is weird as the rules should only restrict inbound connections.

Now I've found the endpoint the next issue is I can't get the status:

```
TypeError: __init__() missing 1 required positional argument: 'standbyDetail'
```
If I run command system getPowerStatus it works and returns:

```
Calling system.getPowerStatus with params None
INFO:songpal.protocol:Calling system.getPowerStatus(None)
{'status': 'active'}
```
This is obviously a different issue though, so I'll close this one and open a new one (probably in a day or two when I've had a bit more time to test out various commands)

**Comment by rytilahti** [comment]
Great to hear you got it working! Time to update the README for tested devices at some point, after we get other kinks you may encounter fixed :-)

I just pushed a fix to master for that standby detail, you can use `pip install -U git+https://github.com/rytilahti/python-songpal.git#egg=python-songpal` to install the git master version for testing.
