### ISSUE TITLE
HT-NT5 support

### ISSUE THREAD

**Issue by tomanderson2** [rytilahti/python-songpal#22]
Thanks for all your efforts implementing this. Just wanted to comment that this works fine via home assistant for a sony HT-NT5. I am able to turn it on / off, change volume, change source and toggle night mode.

Discover gives (not sure if errors matter):

```
Discovering for 3 seconds
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.83:8008/ssdp/notfound' for http://192.168.0.83:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.83:8008/ssdp/notfound' for http://192.168.0.83:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.83:8008/ssdp/notfound' for http://192.168.0.83:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.83:8008/ssdp/notfound' for http://192.168.0.83:8008/ssdp/device-desc.xml
Found HT-NT5 - BAR-2016
* API version: 1.0
* Endpoint: http://192.168.0.83:10000/sony
* Services:
  - Service: guide
  - Service: system
  - Service: audio
  - Service: avContent
```

I always see warnings when interacting with the endpoint (maybe this is common?):

```WARNING:songpal.service:More than on version for {'name': 'getSourceList', 'versions': [{'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getStorageList', 'versions': [{'authLevel': 'generic', 'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSystemInformation', 'versions': [{'version': '1.3'}, {'version': '1.4'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSourceList', 'versions': [{'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getStorageList', 'versions': [{'authLevel': 'generic', 'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSystemInformation', 'versions': [{'version': '1.3'}, {'version': '1.4'}]}, using the first one
```

Without knowing anything about the code; would it make sense to choose the newest version, rather than just the first one?

Is there anything you would like me to test? I have the output from dump_devinfo [here](https://gist.github.com/tomanderson2/46acd48013da08c99e877bb72d742fd1)

**Comment by rytilahti** [comment]
Thanks for reporting back! I updated the readme and added your `dump_devinfo` to the repository for future reference (after masking IP & MAC addresses).

Assuming everything works fine and there is no missing functionality it's fine, if you encounter something not working please create a new issue and we can try and figure out a solution. 

Wrt. version handling, at the moment it's indeed quite messy, the current implementation does not really handle versioning at all, but I never checked what is missing when using the first encountered version. A proper versioning support would be nice, but I do not have time to work on that.

**Comment by tomanderson2** [comment]
Thanks, no issues encountered so far with the functionality I have used.

I tweaked the code a little locally and diffed the difference on a few things when using the newer version, but didn't seem to be much in it. I had "initialPowerOnTime", "lastPowerOnTime" and "bleID" under getSystemInformation which I don't have on the older version. Probably not worth the effort :)

**Comment by rytilahti** [comment]
Thanks again for reporting back, I'm closing this for now.
