### ISSUE TITLE
Support for SRS-ZR5

### ISSUE THREAD

**Issue by thomnico** [rytilahti/python-songpal#24]
Hi,

Would love full support for that one too. Here is the the dumpdev info : https://gist.github.com/thomnico/e3cec8e272d8a2f41f01b54b90872ba8

**Comment by rytilahti** [comment]
Could you be more specific what kind of support is missing? Also please create a PR (you can use the same as for #23 devinfos) for the devinfo so it'll be there when needed, thanks!

**Comment by rytilahti** [comment]
Closing as inactive, please reopen if necessary.
