### ISSUE TITLE
HT-RT5 support (HT-CT790 + two SRS-ZR5) Surround Sound

### ISSUE THREAD

**Issue by ABrauser** [rytilahti/python-songpal#32]
Hello rytilahti,
is it possible to activate and deactivate the Surround Sound via your python-songpal? (I have the HT-RT5. This is a package that includes one HT-CT790 with two SRS-ZR5 Speakers) Its possible to activate and deactivate Sourround Sound via the HT-CT790 Menu or the new Sony "Music Center" App. The "Music Center" app should use the API Interfaces, therefore it should be able to achieve the same goal via your python-songpal.

**Comment by rytilahti** [comment]
I think this depends on how the surround sound is implemented, did you check what settings and sound commands are returning? If there is no setting for this, maybe it is implemented with grouping (see #12)?

**Comment by ABrauser** [comment]
Hmm how exactly can i see the settings and sound commands? sorry but im a bit new in "python" im more like a powershell guy. i have installed python sofar on my windows 10 Client including your python-songpal. This is the result what i get when i discover:

Found HT-CT790 - BAR-2016
* API version: 1.0
* Endpoint: http://192.168.0.16:10000/sony
* Services:
  - Service: guide
  - Service: system
  - Service: audio
  - Service: avContent
Found SRS-ZR5 - MINT1.9.1
* API version: 1.0
* Endpoint: http://192.168.0.17:54480/sony
* Services:
  - Service: guide
  - Service: audio
  - Service: avContent
  - Service: system
  - Service: appControl
Found SRS-ZR5 - MINT1.9.1
* API version: 1.0
* Endpoint: http://192.168.0.18:54480/sony
* Services:
  - Service: guide
  - Service: audio
  - Service: avContent
  - Service: system
  - Service: appControl

**Comment by rytilahti** [comment]
Executing `songpal sound` and `songpal settings` will list most of the settings on my device. But as those are separate devices (endpoints), it may be necessary to do the grouping via UPnP (#12).

**Comment by rytilahti** [comment]
The linked PR has an initial implementation for (de)grouping the devices, I also added some instructions how to test it. To install the branch you can use pip:
```
pip install git+https://github.com/rytilahti/python-songpal.git@groupcontrol
```
Please let me know how it is working (assuming you wasn't able to find something related with those setting commands I gave earlier!

**Comment by ABrauser** [comment]
so i have installed the branch. i had some problems with your command and received following error.

```
PS C:\Users\UnkownStranger> pip install git+https://github.com/rytilahti/python-songpal.git@groupcontrol
Collecting git+https://github.com/rytilahti/python-songpal.git@groupcontrol
  Cloning https://github.com/rytilahti/python-songpal.git (to revision groupcontrol) to c:\users\inu5bon3\appdata\local\temp\pip-req-build-oysbjxdf
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/rytilahti/python-songpal.git C:\Users\UnkownStranger\AppData\Local\Temp\pip-req-build-oysbjxdf
Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

i have installed git for windows and then you command worked via MINGW64. now im not sure if on the "songpal" in the powershell is the same version like in the MINGW64. (Im still kina a python numb) is it possible to verify the songpal version?

can you tell me where i can find the example for grouping and Ungrouping the devices? im exited to see if it works or not. Because there are a different type of grouping for the HT-RTZ7. One for "Multi-Room" Controlling the same Music on each box and one for "Surround Sound" where the Soundbar is controlling the SRS-ZR5.

PS: Thank you for your support! And greetings from Germany ;-)

**Comment by rytilahti** [comment]
Simply type `songpal group` to see if the command is known to it. `songpal --version` would display the version number, but as it doesn't differ for that branch it cannot be used to check it.

Did you check what do `songpal settings` and `songpal sound` list to you? Do you see any relevant settings (you can paste the output here if you want)? I think you'll find the "surround sound" mode under those settings.

See the PR description for instructions how to test the UPnP grouping functionality, this is likely the multiroom functionality you are describing. In three steps:
1. `songpal discover` to locate the UPnP URL for the master device, and the UUIDs for the slaves
2. `songpal group --url <UPnP URL of the master>  create <name of the group> uuid:first:device uuid:second:device ..`
3. `songpal group --url <UPnP URL of the master>  abort` to remove the group.

If you execute a command with `--help` at the end, it will display some help to you, e.g., `volume --help`:
```
Usage: songpal group volume [OPTIONS] VOLUME

  Adjust volume [-100, 100]

Options:
  --help  Show this message and exit.

```

Hope this helps, you are welcome and greetings back!

**Comment by ABrauser** [comment]
so, songpal group says:
```PS C:\Users\UnkownStranger> songpal group
Usage: songpal [OPTIONS] COMMAND [ARGS]...
Try "songpal --help" for help.

Error: No such command "group".
PS C:\Users\UnkownStranger> songpal --version
songpal, version 0.0.8
PS C:\Users\UnkownStranger> songpal discover
Discovering for 3 seconds
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
Found HT-CT790 - BAR-2016
* API version: 1.0
* Endpoint: http://192.168.0.16:10000/sony
* Services:
  - Service: guide
  - Service: system
  - Service: audio
  - Service: avContent
Found SRS-ZR5 - MINT1.9.1
* API version: 1.0
* Endpoint: http://192.168.0.17:54480/sony
* Services:
  - Service: guide
  - Service: audio
  - Service: avContent
  - Service: system
  - Service: appControl
Found SRS-ZR5 - MINT1.9.1
* API version: 1.0
* Endpoint: http://192.168.0.18:54480/sony
* Services:
  - Service: guide
  - Service: audio
  - Service: avContent
  - Service: system
  - Service: appControl
```

So after that songpal settings doesnt work, only if i include the endpoint like this:

```PS C:\Users\Unknownstranger> songpal --endpoint http://192.168.0.16:10000/sony settings
WARNING:songpal.service:More than on version for {'name': 'getSourceList', 'versions': [{'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getStorageList', 'versions': [{'authLevel': 'generic', 'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSystemInformation', 'versions': [{'version': '1.3'}, {'version': '1.4'}]}, using the first one
Sound Settings (deviceConfig)
  * ClearAudio+  (clearAudio, value: [1mon[0m, type: booleanTarget)
    - Ein (on)
  * Sound Field (soundField, value: [1mclearAudio[0m, type: enumTarget)
    - ClearAudio+  (clearAudio)
    - Movie (movie)
    - Music (music)
    - Sports (sports)
    - Game Studio (game)
    - Standard (standard)
  * Night (nightMode, value: [1moff[0m, type: booleanTarget)
    - Ein (on)
    - Aus (off)
  * Voice (voice, value: [1mtype1[0m, type: enumTarget)
    - Up Off (type1)
    - Up 1 (type2)
    - Up 2 (type3)
  * Subwoofer-Lautstärke (subwooferLevel, value: [1m6[0m, type: integerTarget)
    - Subwoofer-Lautstärke (subwooferLevel)
  Toneinstellungen (deviceConfig)
    * A/V SYNC (avSyncMs, value: [1m0[0m, type: integerTarget)
      - A/V SYNC (avSyncMs)
    * Dual-Mono (dualMono, value: [1mmain[0m, type: enumTarget)
      - Haupt/Neben (main_sub)
      - Haupt (main)
      - Neben (sub)
Playback Mode (playingControl)
  * Repeat (repeatType, value: [1moff[0m, type: enumTarget)
  * Shuffle (shuffleType, value: [1moff[0m, type: enumTarget)
* Schnellstart/Netzwerk-Standby (quickStartMode, value: [1mon[0m, type: booleanTarget)
  - On (on)
  - Off (off)
* Automatisches Update (swAutoUpdate, value: [1mon[0m, type: booleanTarget)
  - On (on)
  - Off (off)
* Zeitzone (timeZone, value: [1mEurope/Berlin|60[0m, type: stringTarget)
Google Cast (wuTangSetting)
  * Share usage data (privacySetting, value: [1moff[0m, type: booleanTarget)
    - On (on)
    - Off (off)
  * Activate status (activateStatus, value: [1mon[0m, type: booleanTarget)
    - On (on)
    - Off (off)
  * Version number (currentVersion, value: [1m1.21.76349[0m, type: stringTarget)
```
```
PS C:\Users\Unknownstranger> songpal --endpoint http://192.168.0.17:54480/sony settings
WARNING:songpal.service:More than on version for {'name': 'connectBluetoothDevice', 'versions': [{'version': '1.0'}, {'version': '1.1'}]}, using the first one
None (deviceConfig)
  * None (clearAudio, value: [1moff[0m, type: booleanTarget)
    - An (on)
    - Aus (off)
  Equalizer (deviceConfig)
    * None (soundField, value: [1mhiphop[0m, type: enumTarget)
      - R&B / HIP HOP (hiphop)
      - FLAT (standard)
      - ROCK (rock)
      - POP (pop)
      - LATIN (latin)
      - JAZZ (jazz)
      - CLASSIC (classic)
      - CUSTOM (custom)
    Benutzerdef. EQ (deviceConfig)
      * None (100HzBandLevel, value: [1m0[0m, type: integerTarget)
      * None (330HzBandLevel, value: [1m0[0m, type: integerTarget)
Error: Got an error for getCustomEqualizerSettings: [15, 'unsupported operation']
Traceback (most recent call last):
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Unknownstranger\AppData\Local\Programs\Python\Python37\Scripts\songpal.exe\__main__.py", line 9, in <module>
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 32, in wrapper
    raise ex
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 29, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 392, in settings
    await traverse_settings(dev, module.usage, module.settings)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 43, in traverse_settings
    setting.settings, depth + 2)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 43, in traverse_settings
    setting.settings, depth + 2)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 43, in traverse_settings
    setting.settings, depth + 2)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 45, in traverse_settings
    print_settings([await setting.get_value(dev)], depth=depth)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\containers.py", line 387, in get_value
    self.apiMapping.target)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\device.py", line 205, in get_setting
    return await self.services[service][method](target=target)
  File "c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\method.py", line 159, in __call__
    error=res["error"])
songpal.common.SongpalException: Got an error for getCustomEqualizerSettings: [15, 'unsupported operation']
PS C:\Users\Unknownstranger> songpal --endpoint http://192.168.0.17:54480/sony settings`
```

Where do i get the uuid of the slaves?

**Comment by rytilahti** [comment]
You are not running the code from this branch but some previous version, otherwise your discovery would show the UUIDs and the URLs there, and the group command would be available. Unfortunately I have no idea how these things work in Windows, so I cannot help much there. Did the pip install command above install the files in `c:\users\Unknownstranger\appdata\local\programs\python\python37\lib\site-packages\songpal\`?

I just added a quick patch to fix the `Error: Got an error for getCustomEqualizerSettings: [15, 'unsupported operation']` -- you will likely get more settings shown after you fix your installation :-)

edit: actually looking at the output, the settings is working for you above, but not below?! Are you controlling different speakers here (the second output is from .17, which is SRS-ZR5), but the above is from .16? Nevertheless, that should be fixed now.

**Comment by ABrauser** [comment]
so currently im not able to run the installation with your command:
`pip install git+https://github.com/rytilahti/python-songpal.git@groupcontrol`
i receive the following error:

`Unknownstranger@JARVIS MINGW64 ~
$ pip install git+https://github.com/rytilahti/python-songpal.git@groupcontrol
Collecting git+https://github.com/rytilahti/python-songpal.git@groupcontrol
  Cloning https://github.com/rytilahti/python-songpal.git (to revision groupcontrol) to c:\users\Unknownstranger\appdata\local\temp\pip-req-build-9p4mlhfk
Switched to a new branch 'groupcontrol'
Branch 'groupcontrol' set up to track remote branch 'groupcontrol' from 'origin'.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Unknownstranger\AppData\Local\Temp\pip-req-build-9p4mlhfk\setup.py", line 8, in <module>
        with open('songpal/version.py') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'songpal/version.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Unknownstranger\AppData\Local\Temp\pip-req-build-9p4mlhfk\`

This happens inside the powershell and also in the MINGW64. im now try to verify this problem on a raspbi.
The Device with the IP .16 is the Sony Soundbar HT-CT790.  and the 17, aswell the 18 are the SRS-ZR5

edit: command also doesnt work on the raspberrypi -> pip install git+https://github.com/rytilahti/python-songpal.git@groupcontrol

**Comment by rytilahti** [comment]
Now it's installing from the correct branch, but I forgot to add that file when releasing the 0.0.9, sorry for that. The file is now there, so install should work again.

**Comment by rytilahti** [comment]
I just rebased the linked PR on top of the current master, meaning that you need to upgrade async_upnp_client (`pip install -U async_upnp_client`) to its newest version.

Btw, could you please create a PR to add `HT-CT790.json` under devinfos? `songpal dump_devinfo HT-CT790.json` should do the trick (mask IPs and MAC addresses before submitting it if you wish so).

**Comment by ABrauser** [comment]
ty for the update. I was busy the past days, sorry for the late response.  the first command worked: `pip install -U async_upnp_client` the other command says: 
```
PS C:\Users\Batman> songpal dump_devinfo HT-CT790.json
Usage: songpal [OPTIONS] COMMAND [ARGS]...
Try "songpal --help" for help.

Error: No such command "dump_devinfo".
```

**Comment by rytilahti** [comment]
Try `songpal --help` as instructed, it will output usage information. In some click versions(?) the command is `dump-devinfo` (that is, hyphen instead of underscore), so that probably works.

**Comment by ABrauser** [comment]
Hello, so `songpal --endpoint http://192.168.0.16:10000/sony dump-devinfo HT-CT790.json` finally worked.

see attached the json. (I changed the mac's in the file)
[HT-CT790.json.txt](https://github.com/rytilahti/python-songpal/files/2702553/HT-CT790.json.txt)

There is still some error when i do Discover:

```
PS C:\Users\sadlföjkasdölfkjasdf\Desktop> songpal discover
Discovering for 3 seconds
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
ERROR:ssdp:Error '404 Client Error: Not Found for url: http://192.168.0.16:8008/ssdp/notfound' for http://192.168.0.16:8008/ssdp/device-desc.xml
Found HT-CT790 - BAR-2016
* API version: 1.0
* Endpoint: http://192.168.0.16:10000/sony
* UDN: uuid:00000000-0000-1010-8000-ffffffffffffffff (changed)
* UPnP URL: http://192.168.0.16:52323/dmr.xml
* Services:
  - Service: guide
  - Service: system
  - Service: audio
  - Service: avContent
Found SRS-ZR5 - MINT1.9.1
* API version: 1.0
```

**Comment by rytilahti** [comment]
Nothing about surround settings (besides the `notifyWirelessSurroundInfo` notification) in there. Did you try if there are relevant settings with `songpal sound`?

**Comment by ABrauser** [comment]
Nope doesnt looke like:

```
PS C:\Users\sadasfd> songpal --endpoint http://192.168.0.16:10000/sony sound
WARNING:songpal.service:Got duplicate signature for MethodSignature(name='getSourceList', input={'scheme': <class 'str'>}, output={'source': <class 'str'>, 'title': <class 'str'>, 'isPlayable': 'bool', 'isBrowsable': 'bool', 'playAction': <class 'str'>, 'outputs': 'string*', 'meta': <class 'str'>, 'iconUrl': <class 'str'>, 'protocols': 'string*', 'upnpOperationInfo': 'UpnpOperationInfo'}, version='1.2'), existing was <Method avContent.getSourceList({'scheme': <class 'str'>}) -> {'iconUrl': <class 'str'>,
 'isBrowsable': 'bool',
 'isPlayable': 'bool',
 'meta': <class 'str'>,
 'outputs': 'string*',
 'playAction': <class 'str'>,
 'source': <class 'str'>,
 'title': <class 'str'>}>. Keeping the existing one
WARNING:songpal.service:Got duplicate signature for MethodSignature(name='getStorageList', input={'uri': <class 'str'>, 'isRegistered': <class 'str'>}, output={'uri': <class 'str'>, 'deviceName': <class 'str'>, 'volumeLabel': <class 'str'>, 'permission': <class 'str'>, 'position': <class 'str'>, 'formattable': <class 'str'>, 'mounted': <class 'str'>, 'wholeCapacityMB': <class 'int'>, 'freeCapacityMB': <class 'int'>, 'systemAreaCapacityMB': <class 'int'>, 'isAvailable': <class 'str'>, 'lun': <class 'int'>, 'type': <class 'str'>, 'protocol': <class 'str'>, 'format': <class 'str'>, 'error': <class 'str'>, 'isRegistered': <class 'str'>, 'registrationDate': <class 'str'>, 'isSqvSupported': <class 'str'>, 'hasNonStandardData': <class 'str'>, 'isProtected': <class 'str'>, 'isLocked': <class 'str'>, 'formatStatus': <class 'str'>, 'finalizeStatus': <class 'str'>, 'timeSecToFinalize': <class 'int'>, 'isSelfRecorded': <class 'str'>, 'isManagementInfoFull': <class 'str'>, 'timeSecToGetContents': <class 'int'>, 'hasUnsupportedContents': <class 'str'>, 'usbDeviceType': <class 'str'>, 'fileSystem': <class 'str'>}, version='1.2'), existing was <Method system.getStorageList({'uri': <class 'str'>}) -> {'deviceName': <class 'str'>,
 'error': <class 'str'>,
 'format': <class 'str'>,
 'formattable': <class 'str'>,
 'formatting': <class 'str'>,
 'freeCapacityMB': <class 'int'>,
 'isAvailable': <class 'str'>,
 'lun': <class 'int'>,
 'mounted': <class 'str'>,
 'permission': <class 'str'>,
 'position': <class 'str'>,
 'systemAreaCapacityMB': <class 'int'>,
 'type': <class 'str'>,
 'uri': <class 'str'>,
 'volumeLabel': <class 'str'>,
 'wholeCapacityMB': <class 'int'>}>. Keeping the existing one
WARNING:songpal.service:Got duplicate signature for MethodSignature(name='getSystemInformation', input=None, output={'product': <class 'str'>, 'region': <class 'str'>, 'language': <class 'str'>, 'model': <class 'str'>, 'serial': <class 'str'>, 'macAddr': <class 'str'>, 'name': <class 'str'>, 'generation': <class 'str'>, 'area': <class 'str'>, 'cid': <class 'str'>, 'helpUrl': <class 'str'>, 'deviceID': <class 'str'>, 'version': <class 'str'>, 'duid': <class 'str'>, 'wirelessMacAddr': <class 'str'>, 'esn': <class 'str'>, 'iconUrl': <class 'str'>, 'ssid': <class 'str'>, 'bdAddr': <class 'str'>, 'initialPowerOnTime': <class 'str'>, 'lastPowerOnTime': <class 'str'>, 'bleID': <class 'str'>}, version='1.4'), existing was <Method system.getSystemInformation(None) -> {'area': <class 'str'>,
 'bdAddr': <class 'str'>,
 'cid': <class 'str'>,
 'deviceID': <class 'str'>,
 'duid': <class 'str'>,
 'esn': <class 'str'>,
 'generation': <class 'str'>,
 'helpUrl': <class 'str'>,
 'iconUrl': <class 'str'>,
 'language': <class 'str'>,
 'macAddr': <class 'str'>,
 'model': <class 'str'>,
 'name': <class 'str'>,
 'product': <class 'str'>,
 'region': <class 'str'>,
 'serial': <class 'str'>,
 'ssid': <class 'str'>,
 'updatableVersion': <class 'str'>,
 'version': <class 'str'>,
 'wirelessMacAddr': <class 'str'>}>. Keeping the existing one
* IDMR_TEXT_FOOTBALL_STRING (footballMode, value: [1moff[0m, type: enumTarget)
  - IDMR_TEXT_NARRATION_ON_STRING (on)
  - IDMR_TEXT_NARRATION_OFF_STRING (on_narration_off)
  - Aus (off)
* Night (nightMode, value: [1moff[0m, type: booleanTarget)
  - Ein (on)
  - Aus (off)
* Voice (voice, value: [1mtype1[0m, type: enumTarget)
  - Up Off (type1)
  - Up 1 (type2)
  - Up 2 (type3)
* Subwoofer-Lautstärke (subwooferLevel, value: [1m8[0m, type: integerTarget)
  - Subwoofer-Lautstärke (subwooferLevel)
* A/V SYNC (avSyncMs, value: [1m0[0m, type: integerTarget)
  - A/V SYNC (avSyncMs)
* Dual-Mono (dualMono, value: [1mmain[0m, type: enumTarget)
  - Haupt/Neben (main_sub)
  - Haupt (main)
  - Neben (sub)
PS C:\Users\sadfsdfsdf>
```

Im pretty sure that is possible to control the Surround Sound via API. Because you can also start the Wireless Surround Sound via the Android "Music Center" App. You can just click on "Soundbar Surround" and then the two Speakers SRS-ZR5 are enslaved by the Soundbar. 
![2018-12-23_01-45-38](https://user-images.githubusercontent.com/41122078/50379811-90ed4880-0654-11e9-9636-6326e58758a5.png)
Is it possible to reverse engine the Command? like space sniff what for information's are sended to the devices?

**Comment by rytilahti** [comment]
Yes, you could sniff the network traffic between your phone and the system, that is probably the easiest way to find out how it functions. I think it will use the grouping function (as implemented in the PR, I hope).

**Comment by rytilahti** [comment]
Closing to inactivity. It would have been great to hear if (and if not) that PR helped with this though..
