### ISSUE TITLE
HT-NT5. Warnings / errors in HA log

### ISSUE THREAD

**Issue by hekm77** [rytilahti/python-songpal#36]
HT-NT5
After updating Home Assistant to 0.85.+ I get warnings / errors in the log
After restart HA:
```
Log Details (WARNING)
Sun Jan 13 2019 08:48:04 GMT+0100 (CET)
Got duplicate signature for MethodSignature(name='getSourceList', input={'scheme': <class 'str'>}, output={'source': <class 'str'>, 'title': <class 'str'>, 'isPlayable': 'bool', 'isBrowsable': 'bool', 'playAction': <class 'str'>, 'outputs': 'string*', 'meta': <class 'str'>, 'iconUrl': <class 'str'>, 'protocols': 'string*', 'upnpOperationInfo': 'UpnpOperationInfo'}, version='1.2'), existing was <Method avContent.getSourceList({'scheme': <class 'str'>}) -> {'iconUrl': <class 'str'>,
 'isBrowsable': 'bool',
 'isPlayable': 'bool',
 'meta': <class 'str'>,
 'outputs': 'string*',
 'playAction': <class 'str'>,
 'source': <class 'str'>,
 'title': <class 'str'>}>. Keeping the existing one

Log Details (WARNING) 
Sun Jan 13 2019 08:48:05 GMT+0100 (CET)
Got duplicate signature for MethodSignature(name='getStorageList', input={'uri': <class 'str'>, 'isRegistered': <class 'str'>}, output={'uri': <class 'str'>, 'deviceName': <class 'str'>, 'volumeLabel': <class 'str'>, 'permission': <class 'str'>, 'position': <class 'str'>, 'formattable': <class 'str'>, 'mounted': <class 'str'>, 'wholeCapacityMB': <class 'int'>, 'freeCapacityMB': <class 'int'>, 'systemAreaCapacityMB': <class 'int'>, 'isAvailable': <class 'str'>, 'lun': <class 'int'>, 'type': <class 'str'>, 'protocol': <class 'str'>, 'format': <class 'str'>, 'error': <class 'str'>, 'isRegistered': <class 'str'>, 'registrationDate': <class 'str'>, 'isSqvSupported': <class 'str'>, 'hasNonStandardData': <class 'str'>, 'isProtected': <class 'str'>, 'isLocked': <class 'str'>, 'formatStatus': <class 'str'>, 'finalizeStatus': <class 'str'>, 'timeSecToFinalize': <class 'int'>, 'isSelfRecorded': <class 'str'>, 'isManagementInfoFull': <class 'str'>, 'timeSecToGetContents': <class 'int'>, 'hasUnsupportedContents': <class 'str'>, 'usbDeviceType': <class 'str'>, 'fileSystem': <class 'str'>}, version='1.2'), existing was <Method system.getStorageList({'uri': <class 'str'>}) -> {'deviceName': <class 'str'>,
 'error': <class 'str'>,
 'format': <class 'str'>,
 'formattable': <class 'str'>,
 'formatting': <class 'str'>,
 'freeCapacityMB': <class 'int'>,
 'isAvailable': <class 'str'>,
 'lun': <class 'int'>,
 'mounted': <class 'str'>,
 'permission': <class 'str'>,
 'position': <class 'str'>,
 'systemAreaCapacityMB': <class 'int'>,
 'type': <class 'str'>,
 'uri': <class 'str'>,
 'volumeLabel': <class 'str'>,
 'wholeCapacityMB': <class 'int'>}>. Keeping the existing one

Log Details (WARNING)
Sun Jan 13 2019 08:48:05 GMT+0100 (CET)
Got duplicate signature for MethodSignature(name='getSystemInformation', input=None, output={'product': <class 'str'>, 'region': <class 'str'>, 'language': <class 'str'>, 'model': <class 'str'>, 'serial': <class 'str'>, 'macAddr': <class 'str'>, 'name': <class 'str'>, 'generation': <class 'str'>, 'area': <class 'str'>, 'cid': <class 'str'>, 'helpUrl': <class 'str'>, 'deviceID': <class 'str'>, 'version': <class 'str'>, 'duid': <class 'str'>, 'wirelessMacAddr': <class 'str'>, 'esn': <class 'str'>, 'iconUrl': <class 'str'>, 'ssid': <class 'str'>, 'bdAddr': <class 'str'>, 'initialPowerOnTime': <class 'str'>, 'lastPowerOnTime': <class 'str'>, 'bleID': <class 'str'>}, version='1.4'), existing was <Method system.getSystemInformation(None) -> {'area': <class 'str'>,
 'bdAddr': <class 'str'>,
 'cid': <class 'str'>,
 'deviceID': <class 'str'>,
 'duid': <class 'str'>,
 'esn': <class 'str'>,
 'generation': <class 'str'>,
 'helpUrl': <class 'str'>,
 'iconUrl': <class 'str'>,
 'language': <class 'str'>,
 'macAddr': <class 'str'>,
 'model': <class 'str'>,
 'name': <class 'str'>,
 'product': <class 'str'>,
 'region': <class 'str'>,
 'serial': <class 'str'>,
 'ssid': <class 'str'>,
 'updatableVersion': <class 'str'>,
 'version': <class 'str'>,
 'wirelessMacAddr': <class 'str'>}>. Keeping the existing one
```
Sometimes when I listen spotify on my soundbar:
```
Log Details (WARNING)
Sun Jan 13 2019 13:03:04 GMT+0100 (CET)
Got non-handled content change: ContentChange(contentKind='service', service='netService:audio?service=spotify', source='netService:audio', uri='netService:audio?service=spotify', applicationName=None)
Log Details (ERROR)
Sun Jan 13 2019 13:03:04 GMT+0100 (CET)
Got disconnected with Unable to make a request: 'NoneType' object is not subscriptable: None, trying to reconnect.

Log Details (WARNING)
Sun Jan 13 2019 16:34:37 GMT+0100 (CET)
Got non-handled content change: ContentChange(contentKind='service', service='netService:audio?service=spotify', source='netService:audio', uri='netService:audio?service=spotify', applicationName=None)
Log Details (ERROR)
Sun Jan 13 2019 16:34:37 GMT+0100 (CET)
Got disconnected with Unable to make a request: 'NoneType' object is not subscriptable: None, trying to reconnect.
```

**Comment by rytilahti** [comment]
I'm not sure what is causing the error there as there is no information which method it is trying to call. Could you enable some more logging, i.e., adjust your `configuration.yaml` to have `songpal: debug` for the logger?

If you want to disable the warning about non-handled content change, you could adjust the `homeassistant/media_player/songpal.py` for the time being (from warning to debug, like done referenced PR).

**Comment by hekm77** [comment]
Errors at 
20:18:51
20:38:53
20:47:31
[home-assistant.log](https://github.com/rytilahti/python-songpal/files/2753554/home-assistant.log)

**Comment by rytilahti** [comment]
Those are just warnings which shouldn't have an effect on functionality, the ones that would be interesting are when
```
Got disconnected with Unable to make a request: 'NoneType' object is not subscriptable: None, trying to reconnect.
```
happens.

**Comment by hekm77** [comment]
Thank you.
No warnings after restarting Home Assistant now.

But I get errors every time after switching source from remote control or UI.
The status of the soundbar becomes unavailable for 10 seconds.
[home-assistant.log](https://github.com/rytilahti/python-songpal/files/2799039/home-assistant.log)

**Comment by rytilahti** [comment]
Ok, that is odd, something with the notifications is not working correctly as this code path is only invoked from one call-site... 

To debug this, you would need to modify the songpal/device.py of your installation (the error comes from this ConnectChange:  https://github.com/rytilahti/python-songpal/blob/master/songpal/device.py#L456) to add this line:
```
_LOGGER.error("notification error", exc_info=True)
```
just above the `handle_notification` and then you will get a complete stacktrace for this error.

As a temporary solution you can also modify the `media_player/songpal.py` at homeassistant's end to disable the push updates and use the old-style polling (look for `poll` and set that to `True`). But I hope you can provide me a full stacktrace so I can fix this for good :-)

**Comment by hekm77** [comment]
> stacktrace for this error

[home-assistant.log](https://github.com/rytilahti/python-songpal/files/2799242/home-assistant.log)

**Comment by rytilahti** [comment]
Ok, could you modify `notification.py` to log the contents of `self.apiMappingUpdate`? That is a SettingsChange notification, which for some reason does not contain the new value, so I think I need to guard it somehow.

As a temporary solution you could wrap it around a check:
```
if "currentValue" in self.apiMappingUpdate:
    self.currentValue = self.apiMappingUpdate["currentValue"]
else:
    self.currentValue = None
```

**Comment by hekm77** [comment]
Sorry, I did not understand what needs to be added or changed in the `notification.py`

**Comment by rytilahti** [comment]
Sorry for being unclear, simply replace this method: https://github.com/rytilahti/python-songpal/blob/master/songpal/notification.py#L105
with:
```
    def __attrs_post_init__(self):
        _LOGGER.error("mapping: %s", self.apiMappingUpdate)
        self.currentValue = self.apiMappingUpdate["currentValue"] if "currentValue" in self.apiMappingUpdate else None
        self.target = self.apiMappingUpdate["target"]
```

**Comment by hekm77** [comment]
Now I understand :)
Thanks.
[home-assistant.log](https://github.com/rytilahti/python-songpal/files/2800388/home-assistant.log)

**Comment by rytilahti** [comment]
Hmm, that's weird, there is no apiMappingUpdate at all.. I will need more information to see what is happening, could you revert the function back to original and just add `_LOGGER.error("%s %s %s %s %s", self.titleTextID, self.guideTextID, self.isAvailable, self.type, self.title)` in the beginning of `__attrs_post_init__`?

For the time being you can comment those two existing lines, homeassistant does not currently track any settings so that's okay.

**Comment by hekm77** [comment]
Ok.
[home-assistant.log](https://github.com/rytilahti/python-songpal/files/2801602/home-assistant.log)

**Comment by rytilahti** [comment]
That PR should fix the issue, could you test and confirm that everything works fine with it? The easiest way is to simply replace your existing notification with the linked file (https://raw.githubusercontent.com/rytilahti/python-songpal/b8ed2b4e4ca3e328aa8419aabef4a4cbebc1ffa2/songpal/notification.py), if you are not comfortable with git.

**Comment by hekm77** [comment]
Thank you very much.
This solved the problem. No errors. The device is always available. Everything works fine.
[home-assistant.log](https://github.com/rytilahti/python-songpal/files/2804978/home-assistant.log)

**Comment by hekm77** [comment]
Sorry, but I found another issue.
If I use the _Music Services_ Spotify or Google Cast, and at this time I restarted Home Assistant, then after restarting, `media_player.sony_htnt5` disappears from the entities.
It helps only source changing from the remote control. `media_player.sony_htnt5` becomes available.
I hope clearly explained.
[home-assistant.log](https://github.com/rytilahti/python-songpal/files/2830979/home-assistant.log)

**Comment by rytilahti** [comment]
Ah, indeed, the services are a bit tricky... For the time being you could modify the homeassistant platform and replace:
```
    @property
    def source(self):
        """Return currently active source."""
        return self._active_source.title
```
with
```
    @property
    def source(self):
        """Return currently active source."""
        if self._active_source is not None:
            return self._active_source.title
```

It won't display then any active source, but does not crash either. I'll have to figure out how to fix it properly when I get some time for it.

**Comment by hekm77** [comment]
After upgrading HA(0.87.1) and songpal(0.10) all works without errors.
