### ISSUE TITLE
Audio Control API

### ISSUE THREAD

**Issue by freke** [rytilahti/python-songpal#4]
Something you might find interesting ;-)

https://developer.sony.com/develop/audio-control-api/

Best Regards,

David Åberg
Sony Developer World

**Comment by rytilahti** [comment]
Hi David, and thanks a lot for pointing this out, had I known about this in the past! :-) Do you happen to know if this is available as a PDF or some other, easier-to-search format?

From a quick look I got quite a few things right (thanks to well-designed, introspectable parts of the API!) but a spec is always nice to have ;-). This will be very helpful in the future, and maybe it will even spark someone to contribute fixes and/or implement missing functionalities.

**Comment by freke** [comment]
Since it was only released a couple of weeks ago, it was difficult to notify earlier
Unfortunately for the moment there are no pdf or any other format available, (will see what I can do about that and if we can get it more searchable).
