### ISSUE TITLE
"no such option: --endpoint" error

### ISSUE THREAD

**Issue by jimsmt** [rytilahti/python-songpal#47]
songpal version 0.0.9.1

I can use the command line to discover my music server's endpoint, but when I want to use other feature, I always get this error message

```
Endpoint is required except when with 'discover'!
Usage: songpal list-all [OPTIONS]
Try "songpal list-all --help" for help.

Error: no such option: --endpoint
```

although i have already set the endpoint as advised on the wiki page, like this

./songpal list-all --endpoint http://192.168.2.240:60200/sony

**Comment by rytilahti** [comment]
The `--endpoint` has to be before the command (as it is a global option, not an option for `list-all` command).

**Comment by jimsmt** [comment]
Thanks, I found that too
