### ISSUE TITLE
Got unknowns for ContentChange

### ISSUE THREAD

**Issue by tomanderson2** [rytilahti/python-songpal#48]
Just noticed a bunch of warnings for songpal in my HA log that I wanted to share (because it told me to!);

`[songpal.containers] Got unknowns for ContentChange: {'stateInfo': {'state': 'STOPPED', 'supplement': 'noMedia'}} - please create an issue!`

Happy to help debug / test if needed.

**Comment by rytilahti** [comment]
Thanks, this will get fixed at some point. At the moment, this information is not used by homeassistant to detect if playback has ended or not, but this information could be used to do just that.
