### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by peregrinus** [rytilahti/python-songpal#58]
Unable to control HT-ZF9 after upgrading from 0.10 to 0.11.1

Functional:
![image](https://user-images.githubusercontent.com/1098005/67132944-59d8cb00-f256-11e9-87db-7361f59a8eb5.png)

Decoding issue:
![image](https://user-images.githubusercontent.com/1098005/67132948-69f0aa80-f256-11e9-8d1b-6d0370ccbd57.png)

pip list:
Package           Version   Location
----------------- --------- ------------------------------------------
aiohttp           3.6.2
altgraph          0.15
arrow             0.12.1
asn1crypto        1.0.1
astroid           2.1.0
async-timeout     3.0.1
async-upnp-client 0.14.11
attrs             17.4.0
certifi           2019.9.11
cffi              1.12.3
chardet           3.0.4
Click             7.0
click-configfile  0.2.3
colorama          0.4.1
configparser      3.5.0
cryptography      2.7
defusedxml        0.6.0
dnspython         1.15.0
docxtpl           0.4.13
easygui           0.98.1
future            0.16.0
idna              2.8
idna-ssl          1.1.0
ipwhois           1.0.0
isort             4.3.4
Jinja2            2.10
jsonref           0.1
lazy-object-proxy 1.3.1
lxml              4.2.3
macholib          1.9
markdown2         2.3.5
MarkupSafe        1.0
mccabe            0.6.1
multidict         4.5.2
Naked             0.1.31
ntlm-auth         1.4.0
pefile            2017.11.5
pip               19.2.3
psutil            5.6.3
pycparser         2.19
pycryptodome      3.9.0
pycryptodomex     3.9.0
PyInstaller       3.3.1
pylint            2.2.2
PyPDF3            1.0.1
pyperclip         1.7.0
pypiwin32         223
python-dateutil   2.7.3
python-didl-lite  1.2.4
python-docx       0.8.6
python-songpal    0.11.1
python-whois      0.7.0
pytz              2019.3
pywin32           223
PyYAML            3.12
pyzipper          0.3.1
ramlfications     0.1.9
requests          2.22.0
requests-ntlm     1.1.0
setuptools        28.8.0
shellescape       3.4.1
six               1.11.0
SQLAlchemy        1.2.9
SQLAlchemy-Utils  0.33.3
termcolor         1.1.0
tqdm              4.36.1
typed-ast         1.3.1
typing-extensions 3.7.4
tzlocal           2.0.0
urllib3           1.25.6
voluptuous        0.11.7
wrapt             1.11.1
xmltodict         0.11.0
yarl              1.3.0

**Comment by rytilahti** [comment]
Could you please try with `--debug` or use wireshark to see how the response looks like? I don't currently have access to a device at the moment so I cannot try it out myself.

You could also manually modify that line (104 in songpal/device.py) as described on the second option here: https://docs.aiohttp.org/en/stable/client_advanced.html#disabling-content-type-validation-for-json-responses to see if it helps.

**Comment by peregrinus** [comment]
Thank you for the response! The option to disable the content type check resolved the issue. See screenshot below of the change as per your link. I've included the wireshark of the response i get when i try power on as well. Looks like its due to a lack of proper HTTP content type response headers from the Sony device, no surprises there! 

![image](https://user-images.githubusercontent.com/1098005/67197346-5016b980-f448-11e9-81a9-4fa56d3e4537.png)

**Request:**
POST /sony/guide HTTP/1.1
Host: 192.168.0.252:10000
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.7 aiohttp/3.6.2
Content-Length: 76

{"method": "getSupportedApiInfo", "params": [{}], "id": 1, "version": "1.0"}

**Response:**
HTTP/1.1 200 OK
Connection: close
Content-Length: 4523

{"result":[[{"apis": [{"versions": [{"version": "1.1"}],"name": "getSoundSettings"},{"versions": [{"version": "1.0"}],"name": "getSpeakerSettings"},{"versions": [{"version": "1.1"}],"name": "getVolumeInformation"},{"versions": [{"version": "1.1"}],"name": "setAudioMute"},{"versions": [{"version": "1.1"}],"name": "setAudioVolume"},{"versions": [{"version": "1.1"}],"name": "setSoundSettings"},{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "setSpeakerSettings"},{"name":"switchNotifications","versions":[{"protocols":["websocket:jsonizer"],"version":"1.0"}]}],"service": "audio","protocols": ["xhrpost:jsonizer","websocket:jsonizer"],"notifications": [{"versions": [{"version": "1.0"}],"name": "notifyVolumeInformation"}]}, {"apis": [{"versions": [{"version": "1.0"}],"name": "getAvailablePlaybackFunction"},{"versions": [{"version": "1.0"}],"name": "getBluetoothSettings"},{"versions": [{"version": "1.0"}],"name": "getCurrentExternalTerminalsStatus"},{"versions": [{"version": "1.0"}],"name": "getPlaybackModeSettings"},{"versions": [{"version": "1.2"}],"name": "getPlayingContentInfo"},{"versions": [{"version": "1.0"}],"name": "getSchemeList"},{"versions": [{"version": "1.2"}],"name": "getSourceList"},{"versions": [{"version": "1.0"}],"name": "getSupportedPlaybackFunction"},{"versions": [{"version": "1.1"}],"name": "pausePlayingContent"},{"versions": [{"version": "1.0"}],"name": "scanPlayingContent"},{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "setBluetoothSettings"},{"versions": [{"version": "1.1"}],"name": "setPlaybackModeSettings"},{"versions": [{"version": "1.2"}],"name": "setPlayContent"},{"versions": [{"version": "1.0"}],"name": "setPlayNextContent"},{"versions": [{"version": "1.0"}],"name": "setPlayPreviousContent"},{"versions": [{"version": "1.1"}],"name": "stopPlayingContent"},{"name":"switchNotifications","versions":[{"protocols":["websocket:jsonizer"],"version":"1.0"}]}],"service": "avContent","protocols": ["xhrpost:jsonizer","websocket:jsonizer"],"notifications": [{"versions": [{"version": "1.0"}],"name": "notifyAvailablePlaybackFunction"},{"versions": [{"authLevel": "private","version": "1.0"}],"name": "notifyPlayingContentInfo"}]}, {"apis": [{"versions": [{"version": "1.0"}],"name": "getSupportedApiInfo"}],"service": "guide","protocols": ["websocket:jsonizer"]}, {"apis": [{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "actSWUpdate"},{"versions": [{"version": "1.0"}],"name": "connectBluetoothDevice"},{"versions": [{"version": "1.0"}],"name": "getAlexaDeviceInfo"},{"versions": [{"version": "1.0"}],"name": "getAlexaRegistrationStatus"},{"versions": [{"version": "1.0"}],"name": "getDeviceMiscSettings"},{"versions": [{"version": "1.0"}],"name": "getInterfaceInformation"},{"versions": [{"version": "1.0"}],"name": "getPowerSettings"},{"versions": [{"version": "1.1"}],"name": "getPowerStatus"},{"versions": [{"version": "1.1"}],"name": "getSettingsTree"},{"versions": [{"version": "1.2"}],"name": "getStorageList"},{"versions": [{"version": "1.0"}],"name": "getSWUpdateInfo"},{"versions": [{"version": "1.4"}],"name": "getSystemInformation"},{"versions": [{"version": "1.0"}],"name": "getSystemSupportedFeature"},{"versions": [{"version": "1.0"}],"name": "getWuTangInfo"},{"versions": [{"version": "1.0"}],"name": "setAlexaRegistrationInfo"},{"versions": [{"version": "1.0"}],"name": "setClientInfo"},{"versions": [{"version": "1.0"}],"name": "setDeviceMiscSettings"},{"versions": [{"version": "1.0"}],"name": "setPowerSettings"},{"versions": [{"version": "1.1"}],"name": "setPowerStatus"},{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "setSleepTimerSettings"},{"versions": [{"authLevel":"generic","version": "1.0"}],"name": "setWuTangInfo"},{"versions": [{"version": "1.0"}],"name": "unregistAlexaDevice"},{"versions": [{"version": "1.0"}],"name": "getVoiceCommandGuide"},{"name":"switchNotifications","versions":[{"protocols":["websocket:jsonizer"],"version":"1.0"}]}],"service": "system","protocols": ["xhrpost:jsonizer","websocket:jsonizer"],"notifications": [{"versions": [{"authLevel": "none","version": "1.0"}],"name": "notifyAlexaRegistrationStatus"},{"versions": [{"authLevel": "none","version": "1.0"}],"name": "notifyPowerStatus"},{"versions": [{"authLevel": "none","version": "1.1"}],"name": "notifySettingsUpdate"},{"versions": [{"authLevel": "generic","version": "1.1"}],"name": "notifyStorageStatus"},{"versions": [{"authLevel": "none","version": "1.0"}],"name": "notifySWUpdateInfo"}]}]],"id":1}

**Comment by rytilahti** [comment]
Glad to hear it's working, I'll prepare a bugfix release containing the patch later tonight.
