### ISSUE TITLE
Hassio's latest update makes songpal disappear

### ISSUE THREAD

**Issue by Theiamania** [rytilahti/python-songpal#67]
My settings work and I can control my DN1080 perfectly from the first moment. But this morning I applied an HA update and songpal is no longer available on my system.

It is no longer available in Services and my DN1080 only has the option to delete.

I have erased the device and tried to add it again, but since songpal is no longer available, its lines in configuration.yaml (the same from the beginning) do not take effect.

media_player:
  - platform: songpal
    name: Sony STR-DN1080
    endpoint: http://192.168.0.15:10000/sony

Anyone know why?

Home Assistant 0.108.3
<img width="309" alt="screenshot" src="https://user-images.githubusercontent.com/1210407/79145552-215b1980-7dc1-11ea-8b52-5aee124581e8.png">

**Comment by rytilahti** [comment]
Take a look at the logs, search for songpal to see if there are any relevant entries.

**Comment by Theiamania** [comment]
Sorry I found MY mistake. After the update the server rebooted and at that time I was editing configuration.yaml, and it contained some unfinished and uncorrected changes that have caused this error.
