### ISSUE TITLE
Volume down error

### ISSUE THREAD

**Issue by hekm77** [rytilahti/python-songpal#7]
Sony HT-NT5
`songpal, version 0.0.6`
```
songpal --endpoint http://192.168.1.132:10000/sony volume -5
WARNING:songpal.service:More than on version for {'name': 'getSourceList', 'versions': [{'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getStorageList', 'versions': [{'authLevel': 'generic', 'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSystemInformation', 'versions': [{'version': '1.3'}, {'version': '1.4'}]}, using the first one
Error: no such option: -5
```

**Comment by rytilahti** [comment]
Try `songpal --endpoint http://192.168.1.132:10000/sony volume -- -5` as `-` is interpreted by your shell in this case.

**Comment by hekm77** [comment]
Hi.
If I use `volume -- -5` the volume goes up.
```
pi@raspberrypi:~ $ songpal --endpoint http://192.168.1.132:10000/sony volume -- -5
WARNING:songpal.service:More than on version for {'name': 'getSourceList', 'versions': [{'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getStorageList', 'versions': [{'authLevel': 'generic', 'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSystemInformation', 'versions': [{'version': '1.3'}, {'version': '1.4'}]}, using the first one
Setting volume to -5
Volume: 1/50
pi@raspberrypi:~ $ songpal --endpoint http://192.168.1.132:10000/sony volume -- -5
WARNING:songpal.service:More than on version for {'name': 'getSourceList', 'versions': [{'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getStorageList', 'versions': [{'authLevel': 'generic', 'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSystemInformation', 'versions': [{'version': '1.3'}, {'version': '1.4'}]}, using the first one
Setting volume to -5
Volume: 6/50
pi@raspberrypi:~ $ songpal --endpoint http://192.168.1.132:10000/sony volume -- -5
WARNING:songpal.service:More than on version for {'name': 'getSourceList', 'versions': [{'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getStorageList', 'versions': [{'authLevel': 'generic', 'version': '1.1'}, {'version': '1.2'}]}, using the first one
WARNING:songpal.service:More than on version for {'name': 'getSystemInformation', 'versions': [{'version': '1.3'}, {'version': '1.4'}]}, using the first one
Setting volume to -5
Volume: 11/50
```

**Comment by rytilahti** [comment]
Ok, looks like it fails just as with XT3, I have not found a way to make it work (I just added it as it was documented here https://developer.sony.com/develop/audio-control-api/hardware-overview/api-references/svs/setaudiovolume ). So for now you will have to know your target volume to set it.

**Comment by hekm77** [comment]
Thanks for the answer.
But I did this too. 
`curl -d '{"method": "setAudioVolume","id": 1,"params": [{"volume":"-3"}],"version": "1.1"}' http://192.168.1.132:10000/sony/audio`
The volume is still going up

**Comment by rytilahti** [comment]
Indeed, that's a bug in the firmware of the device I suppose. I thought first that it's just a problem with my HT-XT3, but apparently it's more widespread.

**Comment by hekm77** [comment]
If this is a bug in the firmware, can you tell it to the developers? I hope they fix it in the update.

**Comment by rytilahti** [comment]
I wish I'd know a way, maybe @freke has an idea?

**Comment by rytilahti** [comment]
I wish I'd know a way, maybe @freke has an idea?

If there's any homeassistant user with a supported device, I'd encourage testing https://github.com/home-assistant/home-assistant/pull/12143 (and commenting there) before it gets merged (as soon as python 3.4 support for homeassistant gets dropped in a few weeks). I may remove the volume down service call though.

**Comment by freke** [comment]
Hi @hekm77 @rytilahti 
I don't have an HT-NT5 or HT-XT3 but have got the same result from the receivers and soundbars I got, so it seams to be a general problem.
I have notified the engineers in Tokyo, and are now waiting for there response.

Thanks for the feedback

**Comment by freke** [comment]
@hekm77 @rytilahti this should be fixed in the next firmware update.

**Comment by piotrtaras** [comment]
For Sony STR-DN 1070 the error is the same. I don't think it's the firmware because it's up-to-date and Sony Songpal app volume down button works like it should.

**Comment by rytilahti** [comment]
There has been no firmware update since then, at least not for my model. The app itself does not use this functionality, but rather adjusts with an absolute value based on the current volume. Or that is my understanding, anyway.

**Comment by freke** [comment]
This was fixed with firmware update version M41.R.0442 for STR-DN1080 and Sound Bar firmware version M40.R.0444 both was released 2018-10-10. Don't know the release cycle for other devices but any update later than this should have this fixed.
