### ISSUE TITLE
Send command with Bluetooth

### ISSUE THREAD

**Issue by tjiho** [rytilahti/python-songpal#80]
Hi !
I have a CMT-X5CD, which only support bluetooth. It would be awesome to support this kind of device by sending command in Bluetooth.

I don't know how it's hard to achieve and how many code could be reused. If some people have idea how to implement it...
I would love to implement it if it's not too hard to do.

I found an other opensource tool to command sony headphones in bluetooth, there is probably some similarities.
https://github.com/ClusterM/sony-headphones-control

**Comment by rytilahti** [comment]
Hi,

Bluetooth is completely different way to control the devices, so I don't think there is anything in common with the API used by this library. For that reason I think it doesn't belong to this project and I'm closing this issue.

If you are interested in reversing it by yourself, http://nilhcem.com/iot/reverse-engineering-simple-bluetooth-devices and https://reverse-engineering-ble-devices.readthedocs.io/en/latest/protocol_reveng/00_protocol_reveng.html give some ideas on how to approach it.

**Comment by tjiho** [comment]
Thanks Rytilahti for the links.

**Comment by rytilahti** [comment]
You are welcome! Those links are related to bluetooth le reversing, so "regular" bluetooth may work differently, but I have no experience on such devices so I cannot really help you there.
