### ISSUE TITLE
LSPX-S2 works but...

### ISSUE THREAD

**Issue by pasoad** [rytilahti/python-songpal#85]
I confirm the LSPX-S2 model works fine with this integration (source, volume and power control).

But there is a light in this one, any chance to control it also ? :)

![image](https://user-images.githubusercontent.com/46829490/104066998-a36a5880-5202-11eb-9d3f-2aaf6d99623e.png)

**Comment by rytilahti** [comment]
Can you control the lamp using the mobile app?

Anyway, take a look at the `dump-devinfo` command, it will list all available interfaces & methods. I know that some devices have `illumination` service which is currently completely unimplemented, maybe the lamp controls are located under it?

**Comment by pasoad** [comment]
Thanks for your quick reply @rytilahti.

`Can you control the lamp using the mobile app?`

Yes, it's working with the Music Center app

`take a look at the dump-devinfo`

I'm sorry but i don't know how i can do that :)

**Comment by rytilahti** [comment]
Okay, so try first `songpal list-all`. That should list all available commands, but if not, you can also execute `songpal dump-devinfo` which in turn will create a JSON file containing all necessary information. You could take a look at the file and see if there's anything that might indicate lamp/light/so on in there.

Also, if you don't mind, it'd be great if you could create a PR to add the devinfo file to https://github.com/rytilahti/python-songpal/tree/master/devinfos !

**Comment by pasoad** [comment]
I would like to, but i realy don't know where i can use those comands... (i'm a noobs for this)

**Comment by rytilahti** [comment]
Without being more specific it's hard to know exactly how I can help with that. Anyway, take a look at the instructions in README file: https://github.com/rytilahti/python-songpal#installation

**Comment by pasoad** [comment]
I'm sorry. But my questions was about the [integration in Home Assistant](https://www.home-assistant.io/integrations/songpal) and that's why i didn't understand what you asked me to do :)

I just clicked on a link of the integration's doc and arrived here...

**Comment by rytilahti** [comment]
Oh, so this repository is for the backend library (and `songpal` tool) that is used by homeassistant for controlling these devices, https://github.com/rytilahti/python-songpal#installation shows quick installation instructions. After installation, you should be able to control the device using `songpal`, e.g., `songpal discover` to find the endpoint and then use `songpal --endpoint <endpoint url> <some command>` to command the device. `songpal --help` will list all available commands.
