### ISSUE TITLE
Volume up works but Volume down doesn't

### ISSUE THREAD

**Issue by ChrisB-Cloud** [rytilahti/python-songpal#87]
Sony STR-DN1080
iServer:~ localadmin$ songpal volume +5
Setting volume to +5
Zone 1 Volume: 10/55
Zone 2 Volume: -1/55
Zone 4 Volume: -1/55

iServer:~ localadmin$ songpal volume -5
Usage: songpal volume [OPTIONS] [VOLUME]
Try 'songpal volume --help' for help.

Error: no such option: -5

Please advise or fix in next release ;-)

**Comment by rytilahti** [comment]
That's because the shell thinks it is a command-line flag, you could try `songpal volume -- -5` or `songpal volume "-5"`, but keep in mind that some firmware versions do not implement the volume down using relative values correctly.

**Comment by ChrisB-Cloud** [comment]
Hi there and thanks for your prompt response! :-)
I've tried your suggestions and the first one (songpal volume -- -5) works a treat whereas the second one (songpal volume "-5") results in the same error (Error: no such option: -5)
Just for reference, the AVR is running the latest firmware (M41.R.0516)

Thanks again!
