### ISSUE TITLE
Switch to click 8

### ISSUE THREAD

**Issue by dotlambda** [rytilahti/python-songpal#91]
Read about the changes here: https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0

**Comment by rytilahti** [comment]
Is the tool not working anymore on v8? I'm not sure if it makes sense to force a dependency update just for the sake of new release being available :-)

**Comment by dotlambda** [comment]
I find that `songpal --version` is not working, but that might be unrelated to click:
```
$ songpal --version
Traceback (most recent call last):
  File "/nix/store/75m3xfinlzjzapyjww0l8mh149mscpm6-python3.9-click-8.0.1/lib/python3.9/site-packages/click/decorators.py", line 379, in callback
    version = metadata.version(package_name)  # type: ignore
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/importlib/metadata.py", line 551, in version
    return distribution(distribution_name).version
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: songpal
```
I only have success using `metadata.version('python_songpal')` so maybe you should pass `version` or `package_name` to `@version_option`?

**Comment by cdce8p** [comment]
Any updates? Most requirements for Home Assistant do support version 8 by now, this is one of the last ones that doesn't.
Regarding the `--version` flag. According to the changelog, you can pass `package_name=songpal` to `@version_option` that should fix it. To be compatible with both versions 7 and 8, add a dummy `package_name=None` parameter to the `cli` function definition as any unused args are passed to the function itself.

**Comment by rytilahti** [comment]
Thanks for the ping @cdce8p! Passing a dummy parameter didn't work off the bat, and I think adding extra complexity just for the sake of supporting that option for older click versions is not worth it.

**Comment by cdce8p** [comment]
Thanks for the update @rytilahti!

> Passing a dummy parameter didn't work off the bat, and I think adding extra complexity just for the sake of supporting that option for older click versions is not worth it.

😕

I did some experimentation just now, only for myself to see if there is an option. I did find something that does work. Basically choosing the decorator depending on the `click` version. If you like, feel free to copy it.
```py
def version_option_decorator(func):
    if click.__version__.startswith("7."):
        return click.version_option()(func)
    return click.version_option(package_name="python-songpal")(func)


@click. ...
...
@version_option_decorator
@coro
async def cli(ctx, endpoint, debug, websocket, post):
    ...
```

--
Would you be able to do another release soon? That would fix one of the issues for a successful `pip check` run in Home Assistant. https://github.com/home-assistant/core/pull/64058

**Comment by rytilahti** [comment]
@cdce8p I don't think it's worth the effort, the version information is available through other means anyway :-)

I'm waiting on #96 to see if we can squeeze that into the release as this project is not that maintained anymore and it would be great to have it in if it helps some people.

**Comment by cdce8p** [comment]
> I'm waiting on #96 to see if we can squeeze that into the release as this project is not that maintained anymore and it would be great to have it in if it helps some people.

Yeah, no problem. There are a few other conflicts which won't get resolved anytime soon unfortunately. So no need to hurry. Feel free to tag me when you do the requirement update for Home Assistant.

**Comment by rytilahti** [comment]
> Yeah, no problem. There are a few other conflicts which won't get resolved anytime soon unfortunately. So no need to hurry. Feel free to tag me when you do the requirement update for Home Assistant.

Great! :+1: I'll try to remember that, but as it may take some time, take no offense if I forget. I'll still be preparing a PR to get it bumped in homeassistant so if there's a way to follow the PRs per label that'd be an easy way to get informed :-)

**Comment by cdce8p** [comment]
> Great! 👍 I'll try to remember that, but as it may take some time, take no offense if I forget. I'll still be preparing a PR to get it bumped in homeassistant so if there's a way to follow the PRs per label that'd be an easy way to get informed :-)

Don't worry about it. I'll just subscribe to new release then. That will work too.
