### ISSUE TITLE
Inconsistency between `get_update_info` and `SoftwareUpdateChange`

### ISSUE THREAD

**Issue by Flameeyes** [rytilahti/python-songpal#93]
I'm unable to reproduce because there's no software update for the HT-A7000 yet so I can't know this for sure if it's broken, but something feels wrong.

`get_update_info()` returns `SoftwareUpdateInfo` which appears to be a flat class, where `isUpdatable` and `forcedUpdate` (and `estimatedTimeSec`, `target` and `updatableVersion`) are at the same level.

In the documentation, though, `getSWUpdateInfo()` documents the response as having the same structure as the notification, with `isUpdatable` at top-level, and `forcedUpdate` (and `estimatedTimeSec`, `target` and `updatableVersion`) as belonging to the `swInfo` dictionary.

This appears to match the implementation of `SoftwareUpdateChange` where the `swInfo` dictionary is created as `SoftwareUpdateInfo`.

**Comment by rytilahti** [comment]
I'm not using any devices supported by this lib, and the implementation was based on the responses from a device that was not internet-connected, so it may have been malformed.

Feel free to open a PR, if you wish!

**Comment by Flameeyes** [comment]
Folded this into #96!
