### ISSUE TITLE
Heartbeat timeout HT-ZF9

### ISSUE THREAD

**Issue by mduesund** [rytilahti/python-songpal#94]
HT-ZF9 keeps disconnecting. 

First warning:

Logger: homeassistant.components.songpal.media_player
Source: components/songpal/media_player.py:155 
Integration: Sony Songpal (documentation, issues) 
First occurred: 20:23:09 (1 occurrences) 
Last logged: 20:23:09

[HT-ZF9(http://10.0.0.129:10000/sony)] Got disconnected, trying to reconnect

Then:

Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py:658 
First occurred: 20:23:12 (1 occurrences) 
Last logged: 20:23:12

[Stue lydplanke(10.0.0.129):8009] Heartbeat timeout, resetting connection

Finally:

Logger: homeassistant.components.songpal.media_player
Source: components/songpal/media_player.py:182 
Integration: Sony Songpal (documentation, issues) 
First occurred: 20:23:20 (1 occurrences) 
Last logged: 20:23:20

[HT-ZF9(http://10.0.0.129:10000/sony)] Connection reestablished

**Comment by rytilahti** [comment]
For me this sounds like a network issue, considering that both pychromecast and python-songpal websockets are getting disconnected. I'm not sure if there's anything we can do here..

**Comment by mduesund** [comment]
You're probably right, I will try a factory reset on the sony speaker.

**Comment by rytilahti** [comment]
If you [enable debug logging for the integration](https://www.home-assistant.io/integrations/logger/), you should get some more information from songpal at least (https://github.com/home-assistant/core/blob/dev/homeassistant/components/songpal/media_player.py#L160).

**Comment by mduesund** [comment]
Oh and also:

Logger: songpal.service
Source: /usr/local/lib/python3.9/site-packages/songpal/service.py:225 
First occurred: 22:39:12 (2 occurrences) 
Last logged: 22:39:26

Got unknown notification type: notifyStorageStatus - params: [{'isAvailable': 'unknown', 'mounted': 'unmounted', 'uri': 'storage:usb1'}]

**Comment by rytilahti** [comment]
I created a PR to add that storage status notification as it seemed simple enough, but please create separate tickets for different issues in the future :-)
